#!/bin/bash

CMD_PATH=$(realpath $0)
SOURCE_DIR=$(dirname ${CMD_PATH})

COMMON_SYMBOLS="
uc_add_inline_hook \
uc_del_inline_hook \
tb_invalidate_phys_range \
use_idiv_instructions \
arm_arch \
tb_target_set_jmp_target \
have_bmi1 \
have_popcnt \
have_avx1 \
have_avx2 \
have_isa \
have_altivec \
have_vsx \
flush_icache_range \
s390_facilities \
tcg_dump_op \
tcg_dump_ops \
tcg_gen_and_i64 \
tcg_gen_discard_i64 \
tcg_gen_ld16s_i64 \
tcg_gen_ld16u_i64 \
tcg_gen_ld32s_i64 \
tcg_gen_ld32u_i64 \
tcg_gen_ld8s_i64 \
tcg_gen_ld8u_i64 \
tcg_gen_ld_i64 \
tcg_gen_mov_i64 \
tcg_gen_movi_i64 \
tcg_gen_mul_i64 \
tcg_gen_or_i64 \
tcg_gen_sar_i64 \
tcg_gen_shl_i64 \
tcg_gen_shr_i64 \
tcg_gen_st_i64 \
tcg_gen_xor_i64 \
cpu_icount_to_ns \
cpu_is_stopped \
cpu_get_ticks \
cpu_get_clock \
cpu_resume \
qemu_init_vcpu \
cpu_stop_current \
resume_all_vcpus \
vm_start \
address_space_dispatch_compact \
flatview_translate \
address_space_translate_for_iotlb \
qemu_get_cpu \
cpu_address_space_init \
cpu_get_address_space \
cpu_exec_unrealizefn \
cpu_exec_initfn \
cpu_exec_realizefn \
tb_invalidate_phys_addr \
cpu_watchpoint_insert \
cpu_watchpoint_remove_by_ref \
cpu_watchpoint_remove_all \
cpu_watchpoint_address_matches \
cpu_breakpoint_insert \
cpu_breakpoint_remove \
cpu_breakpoint_remove_by_ref \
cpu_breakpoint_remove_all \
cpu_abort \
cpu_physical_memory_test_and_clear_dirty \
memory_region_section_get_iotlb \
flatview_add_to_dispatch \
qemu_ram_get_host_addr \
qemu_ram_get_offset \
qemu_ram_get_used_length \
qemu_ram_is_shared \
qemu_ram_pagesize \
qemu_ram_alloc_from_ptr \
qemu_ram_alloc \
qemu_ram_free \
qemu_map_ram_ptr \
qemu_ram_block_host_offset \
qemu_ram_block_from_host \
qemu_ram_addr_from_host \
cpu_check_watchpoint \
iotlb_to_section \
address_space_dispatch_new \
address_space_dispatch_free \
flatview_read_continue \
address_space_read_full \
address_space_write \
address_space_rw \
cpu_physical_memory_rw \
address_space_write_rom \
cpu_flush_icache_range \
cpu_exec_init_all \
address_space_access_valid \
address_space_map \
address_space_unmap \
cpu_physical_memory_map \
cpu_physical_memory_unmap \
cpu_memory_rw_debug \
qemu_target_page_size \
qemu_target_page_bits \
qemu_target_page_bits_min \
target_words_bigendian \
cpu_physical_memory_is_io \
ram_block_discard_range \
ramblock_is_pmem \
page_size_init \
set_preferred_target_page_bits \
finalize_target_page_bits \
cpu_outb \
cpu_outw \
cpu_outl \
cpu_inb \
cpu_inw \
cpu_inl \
memory_map \
memory_map_io \
memory_map_ptr \
memory_unmap \
memory_free \
flatview_unref \
address_space_get_flatview \
memory_region_transaction_begin \
memory_region_transaction_commit \
memory_region_init \
memory_region_access_valid \
memory_region_dispatch_read \
memory_region_dispatch_write \
memory_region_init_io \
memory_region_init_ram_ptr \
memory_region_size \
memory_region_set_readonly \
memory_region_get_ram_ptr \
memory_region_from_host \
memory_region_get_ram_addr \
memory_region_add_subregion \
memory_region_del_subregion \
memory_region_find \
memory_listener_register \
memory_listener_unregister \
address_space_remove_listeners \
address_space_init \
address_space_destroy \
memory_region_init_ram \
memory_mapping_list_add_merge_sorted \
exec_inline_op \
floatx80_default_nan \
float_raise \
float16_is_quiet_nan \
float16_is_signaling_nan \
float32_is_quiet_nan \
float32_is_signaling_nan \
float64_is_quiet_nan \
float64_is_signaling_nan \
floatx80_is_quiet_nan \
floatx80_is_signaling_nan \
floatx80_silence_nan \
propagateFloatx80NaN \
float128_is_quiet_nan \
float128_is_signaling_nan \
float128_silence_nan \
float16_add \
float16_sub \
float32_add \
float32_sub \
float64_add \
float64_sub \
float16_mul \
float32_mul \
float64_mul \
float16_muladd \
float32_muladd \
float64_muladd \
float16_div \
float32_div \
float64_div \
float16_to_float32 \
float16_to_float64 \
float32_to_float16 \
float32_to_float64 \
float64_to_float16 \
float64_to_float32 \
float16_round_to_int \
float32_round_to_int \
float64_round_to_int \
float16_to_int16_scalbn \
float16_to_int32_scalbn \
float16_to_int64_scalbn \
float32_to_int16_scalbn \
float32_to_int32_scalbn \
float32_to_int64_scalbn \
float64_to_int16_scalbn \
float64_to_int32_scalbn \
float64_to_int64_scalbn \
float16_to_int16 \
float16_to_int32 \
float16_to_int64 \
float32_to_int16 \
float32_to_int32 \
float32_to_int64 \
float64_to_int16 \
float64_to_int32 \
float64_to_int64 \
float16_to_int16_round_to_zero \
float16_to_int32_round_to_zero \
float16_to_int64_round_to_zero \
float32_to_int16_round_to_zero \
float32_to_int32_round_to_zero \
float32_to_int64_round_to_zero \
float64_to_int16_round_to_zero \
float64_to_int32_round_to_zero \
float64_to_int64_round_to_zero \
float16_to_uint16_scalbn \
float16_to_uint32_scalbn \
float16_to_uint64_scalbn \
float32_to_uint16_scalbn \
float32_to_uint32_scalbn \
float32_to_uint64_scalbn \
float64_to_uint16_scalbn \
float64_to_uint32_scalbn \
float64_to_uint64_scalbn \
float16_to_uint16 \
float16_to_uint32 \
float16_to_uint64 \
float32_to_uint16 \
float32_to_uint32 \
float32_to_uint64 \
float64_to_uint16 \
float64_to_uint32 \
float64_to_uint64 \
float16_to_uint16_round_to_zero \
float16_to_uint32_round_to_zero \
float16_to_uint64_round_to_zero \
float32_to_uint16_round_to_zero \
float32_to_uint32_round_to_zero \
float32_to_uint64_round_to_zero \
float64_to_uint16_round_to_zero \
float64_to_uint32_round_to_zero \
float64_to_uint64_round_to_zero \
int64_to_float16_scalbn \
int32_to_float16_scalbn \
int16_to_float16_scalbn \
int64_to_float16 \
int32_to_float16 \
int16_to_float16 \
int64_to_float32_scalbn \
int32_to_float32_scalbn \
int16_to_float32_scalbn \
int64_to_float32 \
int32_to_float32 \
int16_to_float32 \
int64_to_float64_scalbn \
int32_to_float64_scalbn \
int16_to_float64_scalbn \
int64_to_float64 \
int32_to_float64 \
int16_to_float64 \
uint64_to_float16_scalbn \
uint32_to_float16_scalbn \
uint16_to_float16_scalbn \
uint64_to_float16 \
uint32_to_float16 \
uint16_to_float16 \
uint64_to_float32_scalbn \
uint32_to_float32_scalbn \
uint16_to_float32_scalbn \
uint64_to_float32 \
uint32_to_float32 \
uint16_to_float32 \
uint64_to_float64_scalbn \
uint32_to_float64_scalbn \
uint16_to_float64_scalbn \
uint64_to_float64 \
uint32_to_float64 \
uint16_to_float64 \
float16_min \
float16_minnum \
float16_minnummag \
float16_max \
float16_maxnum \
float16_maxnummag \
float32_min \
float32_minnum \
float32_minnummag \
float32_max \
float32_maxnum \
float32_maxnummag \
float64_min \
float64_minnum \
float64_minnummag \
float64_max \
float64_maxnum \
float64_maxnummag \
float16_compare \
float16_compare_quiet \
float32_compare \
float32_compare_quiet \
float64_compare \
float64_compare_quiet \
float16_scalbn \
float32_scalbn \
float64_scalbn \
float16_sqrt \
float32_sqrt \
float64_sqrt \
float16_default_nan \
float32_default_nan \
float64_default_nan \
float128_default_nan \
float16_silence_nan \
float32_silence_nan \
float64_silence_nan \
float16_squash_input_denormal \
float32_squash_input_denormal \
float64_squash_input_denormal \
normalizeFloatx80Subnormal \
roundAndPackFloatx80 \
normalizeRoundAndPackFloatx80 \
int32_to_floatx80 \
int32_to_float128 \
int64_to_floatx80 \
int64_to_float128 \
uint64_to_float128 \
float32_to_floatx80 \
float32_to_float128 \
float32_rem \
float32_exp2 \
float32_log2 \
float32_eq \
float32_le \
float32_lt \
float32_unordered \
float32_eq_quiet \
float32_le_quiet \
float32_lt_quiet \
float32_unordered_quiet \
float64_to_floatx80 \
float64_to_float128 \
float64_rem \
float64_log2 \
float64_eq \
float64_le \
float64_lt \
float64_unordered \
float64_eq_quiet \
float64_le_quiet \
float64_lt_quiet \
float64_unordered_quiet \
floatx80_to_int32 \
floatx80_to_int32_round_to_zero \
floatx80_to_int64 \
floatx80_to_int64_round_to_zero \
floatx80_to_float32 \
floatx80_to_float64 \
floatx80_to_float128 \
floatx80_round \
floatx80_round_to_int \
floatx80_add \
floatx80_sub \
floatx80_mul \
floatx80_div \
floatx80_rem \
floatx80_sqrt \
floatx80_eq \
floatx80_le \
floatx80_lt \
floatx80_unordered \
floatx80_eq_quiet \
floatx80_le_quiet \
floatx80_lt_quiet \
floatx80_unordered_quiet \
float128_to_int32 \
float128_to_int32_round_to_zero \
float128_to_int64 \
float128_to_int64_round_to_zero \
float128_to_uint64 \
float128_to_uint64_round_to_zero \
float128_to_uint32_round_to_zero \
float128_to_uint32 \
float128_to_float32 \
float128_to_float64 \
float128_to_floatx80 \
float128_round_to_int \
float128_add \
float128_sub \
float128_mul \
float128_div \
float128_rem \
float128_sqrt \
float128_eq \
float128_le \
float128_lt \
float128_unordered \
float128_eq_quiet \
float128_le_quiet \
float128_lt_quiet \
float128_unordered_quiet \
floatx80_compare \
floatx80_compare_quiet \
float128_compare \
float128_compare_quiet \
floatx80_scalbn \
float128_scalbn \
softfloat_init \
tcg_optimize \
gen_new_label \
tcg_can_emit_vec_op \
tcg_expand_vec_op \
tcg_register_jit \
tcg_tb_insert \
tcg_tb_remove \
tcg_tb_lookup \
tcg_tb_foreach \
tcg_nb_tbs \
tcg_region_reset_all \
tcg_region_init \
tcg_code_size \
tcg_code_capacity \
tcg_tb_phys_invalidate_count \
tcg_malloc_internal \
tcg_pool_reset \
tcg_context_init \
tcg_tb_alloc \
tcg_prologue_init \
tcg_func_start \
tcg_set_frame \
tcg_global_mem_new_internal \
tcg_temp_new_internal \
tcg_temp_new_vec \
tcg_temp_new_vec_matching \
tcg_temp_free_internal \
tcg_const_i32 \
tcg_const_i64 \
tcg_const_local_i32 \
tcg_const_local_i64 \
tcg_op_supported \
tcg_gen_callN \
tcg_op_remove \
tcg_emit_op \
tcg_op_insert_before \
tcg_op_insert_after \
tcg_cpu_exec_time \
tcg_gen_code \
tcg_gen_op1 \
tcg_gen_op2 \
tcg_gen_op3 \
tcg_gen_op4 \
tcg_gen_op5 \
tcg_gen_op6 \
tcg_gen_mb \
tcg_gen_addi_i32 \
tcg_gen_subfi_i32 \
tcg_gen_subi_i32 \
tcg_gen_andi_i32 \
tcg_gen_ori_i32 \
tcg_gen_xori_i32 \
tcg_gen_shli_i32 \
tcg_gen_shri_i32 \
tcg_gen_sari_i32 \
tcg_gen_brcond_i32 \
tcg_gen_brcondi_i32 \
tcg_gen_setcond_i32 \
tcg_gen_setcondi_i32 \
tcg_gen_muli_i32 \
tcg_gen_div_i32 \
tcg_gen_rem_i32 \
tcg_gen_divu_i32 \
tcg_gen_remu_i32 \
tcg_gen_andc_i32 \
tcg_gen_eqv_i32 \
tcg_gen_nand_i32 \
tcg_gen_nor_i32 \
tcg_gen_orc_i32 \
tcg_gen_clz_i32 \
tcg_gen_clzi_i32 \
tcg_gen_ctz_i32 \
tcg_gen_ctzi_i32 \
tcg_gen_clrsb_i32 \
tcg_gen_ctpop_i32 \
tcg_gen_rotl_i32 \
tcg_gen_rotli_i32 \
tcg_gen_rotr_i32 \
tcg_gen_rotri_i32 \
tcg_gen_deposit_i32 \
tcg_gen_deposit_z_i32 \
tcg_gen_extract_i32 \
tcg_gen_sextract_i32 \
tcg_gen_extract2_i32 \
tcg_gen_movcond_i32 \
tcg_gen_add2_i32 \
tcg_gen_sub2_i32 \
tcg_gen_mulu2_i32 \
tcg_gen_muls2_i32 \
tcg_gen_mulsu2_i32 \
tcg_gen_ext8s_i32 \
tcg_gen_ext16s_i32 \
tcg_gen_ext8u_i32 \
tcg_gen_ext16u_i32 \
tcg_gen_bswap16_i32 \
tcg_gen_bswap32_i32 \
tcg_gen_smin_i32 \
tcg_gen_umin_i32 \
tcg_gen_smax_i32 \
tcg_gen_umax_i32 \
tcg_gen_abs_i32 \
tcg_gen_addi_i64 \
tcg_gen_subfi_i64 \
tcg_gen_subi_i64 \
tcg_gen_andi_i64 \
tcg_gen_ori_i64 \
tcg_gen_xori_i64 \
tcg_gen_shli_i64 \
tcg_gen_shri_i64 \
tcg_gen_sari_i64 \
tcg_gen_brcond_i64 \
tcg_gen_brcondi_i64 \
tcg_gen_setcond_i64 \
tcg_gen_setcondi_i64 \
tcg_gen_muli_i64 \
tcg_gen_div_i64 \
tcg_gen_rem_i64 \
tcg_gen_divu_i64 \
tcg_gen_remu_i64 \
tcg_gen_ext8s_i64 \
tcg_gen_ext16s_i64 \
tcg_gen_ext32s_i64 \
tcg_gen_ext8u_i64 \
tcg_gen_ext16u_i64 \
tcg_gen_ext32u_i64 \
tcg_gen_bswap16_i64 \
tcg_gen_bswap32_i64 \
tcg_gen_bswap64_i64 \
tcg_gen_not_i64 \
tcg_gen_andc_i64 \
tcg_gen_eqv_i64 \
tcg_gen_nand_i64 \
tcg_gen_nor_i64 \
tcg_gen_orc_i64 \
tcg_gen_clz_i64 \
tcg_gen_clzi_i64 \
tcg_gen_ctz_i64 \
tcg_gen_ctzi_i64 \
tcg_gen_clrsb_i64 \
tcg_gen_ctpop_i64 \
tcg_gen_rotl_i64 \
tcg_gen_rotli_i64 \
tcg_gen_rotr_i64 \
tcg_gen_rotri_i64 \
tcg_gen_deposit_i64 \
tcg_gen_deposit_z_i64 \
tcg_gen_extract_i64 \
tcg_gen_sextract_i64 \
tcg_gen_extract2_i64 \
tcg_gen_movcond_i64 \
tcg_gen_add2_i64 \
tcg_gen_sub2_i64 \
tcg_gen_mulu2_i64 \
tcg_gen_muls2_i64 \
tcg_gen_mulsu2_i64 \
tcg_gen_smin_i64 \
tcg_gen_umin_i64 \
tcg_gen_smax_i64 \
tcg_gen_umax_i64 \
tcg_gen_abs_i64 \
tcg_gen_extrl_i64_i32 \
tcg_gen_extrh_i64_i32 \
tcg_gen_extu_i32_i64 \
tcg_gen_ext_i32_i64 \
tcg_gen_concat_i32_i64 \
tcg_gen_extr_i64_i32 \
tcg_gen_extr32_i64 \
tcg_gen_exit_tb \
tcg_gen_goto_tb \
tcg_gen_lookup_and_goto_ptr \
check_exit_request \
tcg_gen_qemu_ld_i32 \
tcg_gen_qemu_st_i32 \
tcg_gen_qemu_ld_i64 \
tcg_gen_qemu_st_i64 \
tcg_gen_atomic_cmpxchg_i32 \
tcg_gen_atomic_cmpxchg_i64 \
tcg_gen_atomic_fetch_add_i32 \
tcg_gen_atomic_fetch_add_i64 \
tcg_gen_atomic_fetch_and_i32 \
tcg_gen_atomic_fetch_and_i64 \
tcg_gen_atomic_fetch_or_i32 \
tcg_gen_atomic_fetch_or_i64 \
tcg_gen_atomic_fetch_xor_i32 \
tcg_gen_atomic_fetch_xor_i64 \
tcg_gen_atomic_fetch_smin_i32 \
tcg_gen_atomic_fetch_smin_i64 \
tcg_gen_atomic_fetch_umin_i32 \
tcg_gen_atomic_fetch_umin_i64 \
tcg_gen_atomic_fetch_smax_i32 \
tcg_gen_atomic_fetch_smax_i64 \
tcg_gen_atomic_fetch_umax_i32 \
tcg_gen_atomic_fetch_umax_i64 \
tcg_gen_atomic_add_fetch_i32 \
tcg_gen_atomic_add_fetch_i64 \
tcg_gen_atomic_and_fetch_i32 \
tcg_gen_atomic_and_fetch_i64 \
tcg_gen_atomic_or_fetch_i32 \
tcg_gen_atomic_or_fetch_i64 \
tcg_gen_atomic_xor_fetch_i32 \
tcg_gen_atomic_xor_fetch_i64 \
tcg_gen_atomic_smin_fetch_i32 \
tcg_gen_atomic_smin_fetch_i64 \
tcg_gen_atomic_umin_fetch_i32 \
tcg_gen_atomic_umin_fetch_i64 \
tcg_gen_atomic_smax_fetch_i32 \
tcg_gen_atomic_smax_fetch_i64 \
tcg_gen_atomic_umax_fetch_i32 \
tcg_gen_atomic_umax_fetch_i64 \
tcg_gen_atomic_xchg_i32 \
tcg_gen_atomic_xchg_i64 \
simd_desc \
tcg_gen_gvec_2_ool \
tcg_gen_gvec_2i_ool \
tcg_gen_gvec_3_ool \
tcg_gen_gvec_4_ool \
tcg_gen_gvec_5_ool \
tcg_gen_gvec_2_ptr \
tcg_gen_gvec_3_ptr \
tcg_gen_gvec_4_ptr \
tcg_gen_gvec_5_ptr \
tcg_gen_gvec_2 \
tcg_gen_gvec_2i \
tcg_gen_gvec_2s \
tcg_gen_gvec_3 \
tcg_gen_gvec_3i \
tcg_gen_gvec_4 \
tcg_gen_gvec_mov \
tcg_gen_gvec_dup_i32 \
tcg_gen_gvec_dup_i64 \
tcg_gen_gvec_dup_mem \
tcg_gen_gvec_dup64i \
tcg_gen_gvec_dup32i \
tcg_gen_gvec_dup16i \
tcg_gen_gvec_dup8i \
tcg_gen_gvec_not \
tcg_gen_vec_add8_i64 \
tcg_gen_vec_add16_i64 \
tcg_gen_vec_add32_i64 \
tcg_gen_gvec_add \
tcg_gen_gvec_adds \
tcg_gen_gvec_addi \
tcg_gen_gvec_subs \
tcg_gen_vec_sub8_i64 \
tcg_gen_vec_sub16_i64 \
tcg_gen_vec_sub32_i64 \
tcg_gen_gvec_sub \
tcg_gen_gvec_mul \
tcg_gen_gvec_muls \
tcg_gen_gvec_muli \
tcg_gen_gvec_ssadd \
tcg_gen_gvec_sssub \
tcg_gen_gvec_usadd \
tcg_gen_gvec_ussub \
tcg_gen_gvec_smin \
tcg_gen_gvec_umin \
tcg_gen_gvec_smax \
tcg_gen_gvec_umax \
tcg_gen_vec_neg8_i64 \
tcg_gen_vec_neg16_i64 \
tcg_gen_vec_neg32_i64 \
tcg_gen_gvec_neg \
tcg_gen_gvec_abs \
tcg_gen_gvec_and \
tcg_gen_gvec_or \
tcg_gen_gvec_xor \
tcg_gen_gvec_andc \
tcg_gen_gvec_orc \
tcg_gen_gvec_nand \
tcg_gen_gvec_nor \
tcg_gen_gvec_eqv \
tcg_gen_gvec_ands \
tcg_gen_gvec_andi \
tcg_gen_gvec_xors \
tcg_gen_gvec_xori \
tcg_gen_gvec_ors \
tcg_gen_gvec_ori \
tcg_gen_vec_shl8i_i64 \
tcg_gen_vec_shl16i_i64 \
tcg_gen_gvec_shli \
tcg_gen_vec_shr8i_i64 \
tcg_gen_vec_shr16i_i64 \
tcg_gen_gvec_shri \
tcg_gen_vec_sar8i_i64 \
tcg_gen_vec_sar16i_i64 \
tcg_gen_gvec_sari \
tcg_gen_gvec_shls \
tcg_gen_gvec_shrs \
tcg_gen_gvec_sars \
tcg_gen_gvec_shlv \
tcg_gen_gvec_shrv \
tcg_gen_gvec_sarv \
tcg_gen_gvec_cmp \
tcg_gen_gvec_bitsel \
tcg_can_emit_vecop_list \
vec_gen_2 \
vec_gen_3 \
vec_gen_4 \
tcg_gen_mov_vec \
tcg_const_zeros_vec \
tcg_const_ones_vec \
tcg_const_zeros_vec_matching \
tcg_const_ones_vec_matching \
tcg_gen_dup64i_vec \
tcg_gen_dup32i_vec \
tcg_gen_dup16i_vec \
tcg_gen_dup8i_vec \
tcg_gen_dupi_vec \
tcg_gen_dup_i64_vec \
tcg_gen_dup_i32_vec \
tcg_gen_dup_mem_vec \
tcg_gen_ld_vec \
tcg_gen_st_vec \
tcg_gen_stl_vec \
tcg_gen_and_vec \
tcg_gen_or_vec \
tcg_gen_xor_vec \
tcg_gen_andc_vec \
tcg_gen_orc_vec \
tcg_gen_nand_vec \
tcg_gen_nor_vec \
tcg_gen_eqv_vec \
tcg_gen_not_vec \
tcg_gen_neg_vec \
tcg_gen_abs_vec \
tcg_gen_shli_vec \
tcg_gen_shri_vec \
tcg_gen_sari_vec \
tcg_gen_cmp_vec \
tcg_gen_add_vec \
tcg_gen_sub_vec \
tcg_gen_mul_vec \
tcg_gen_ssadd_vec \
tcg_gen_usadd_vec \
tcg_gen_sssub_vec \
tcg_gen_ussub_vec \
tcg_gen_smin_vec \
tcg_gen_umin_vec \
tcg_gen_smax_vec \
tcg_gen_umax_vec \
tcg_gen_shlv_vec \
tcg_gen_shrv_vec \
tcg_gen_sarv_vec \
tcg_gen_shls_vec \
tcg_gen_shrs_vec \
tcg_gen_sars_vec \
tcg_gen_bitsel_vec \
tcg_gen_cmpsel_vec \
tb_htable_lookup \
tb_set_jmp_target \
cpu_exec \
cpu_loop_exit_noexc \
cpu_reloading_memory_map \
cpu_loop_exit \
cpu_loop_exit_restore \
cpu_loop_exit_atomic \
tlb_init \
tlb_flush_by_mmuidx \
tlb_flush \
tlb_flush_by_mmuidx_all_cpus \
tlb_flush_all_cpus \
tlb_flush_by_mmuidx_all_cpus_synced \
tlb_flush_all_cpus_synced \
tlb_flush_page_by_mmuidx \
tlb_flush_page \
tlb_flush_page_by_mmuidx_all_cpus \
tlb_flush_page_all_cpus \
tlb_flush_page_by_mmuidx_all_cpus_synced \
tlb_flush_page_all_cpus_synced \
tlb_protect_code \
tlb_unprotect_code \
tlb_reset_dirty \
tlb_set_dirty \
tlb_set_page_with_attrs \
tlb_set_page \
get_page_addr_code_hostp \
get_page_addr_code \
probe_access \
tlb_vaddr_to_host \
helper_ret_ldub_mmu \
helper_le_lduw_mmu \
helper_be_lduw_mmu \
helper_le_ldul_mmu \
helper_be_ldul_mmu \
helper_le_ldq_mmu \
helper_be_ldq_mmu \
helper_ret_ldsb_mmu \
helper_le_ldsw_mmu \
helper_be_ldsw_mmu \
helper_le_ldsl_mmu \
helper_be_ldsl_mmu \
cpu_ldub_mmuidx_ra \
cpu_ldsb_mmuidx_ra \
cpu_lduw_mmuidx_ra \
cpu_ldsw_mmuidx_ra \
cpu_ldl_mmuidx_ra \
cpu_ldq_mmuidx_ra \
cpu_ldub_data_ra \
cpu_ldsb_data_ra \
cpu_lduw_data_ra \
cpu_ldsw_data_ra \
cpu_ldl_data_ra \
cpu_ldq_data_ra \
cpu_ldub_data \
cpu_ldsb_data \
cpu_lduw_data \
cpu_ldsw_data \
cpu_ldl_data \
cpu_ldq_data \
helper_ret_stb_mmu \
helper_le_stw_mmu \
helper_be_stw_mmu \
helper_le_stl_mmu \
helper_be_stl_mmu \
helper_le_stq_mmu \
helper_be_stq_mmu \
cpu_stb_mmuidx_ra \
cpu_stw_mmuidx_ra \
cpu_stl_mmuidx_ra \
cpu_stq_mmuidx_ra \
cpu_stb_data_ra \
cpu_stw_data_ra \
cpu_stl_data_ra \
cpu_stq_data_ra \
cpu_stb_data \
cpu_stw_data \
cpu_stl_data \
cpu_stq_data \
helper_atomic_cmpxchgb_mmu \
helper_atomic_xchgb_mmu \
helper_atomic_fetch_addb_mmu \
helper_atomic_fetch_andb_mmu \
helper_atomic_fetch_orb_mmu \
helper_atomic_fetch_xorb_mmu \
helper_atomic_add_fetchb_mmu \
helper_atomic_and_fetchb_mmu \
helper_atomic_or_fetchb_mmu \
helper_atomic_xor_fetchb_mmu \
helper_atomic_fetch_sminb_mmu \
helper_atomic_fetch_uminb_mmu \
helper_atomic_fetch_smaxb_mmu \
helper_atomic_fetch_umaxb_mmu \
helper_atomic_smin_fetchb_mmu \
helper_atomic_umin_fetchb_mmu \
helper_atomic_smax_fetchb_mmu \
helper_atomic_umax_fetchb_mmu \
helper_atomic_cmpxchgw_le_mmu \
helper_atomic_xchgw_le_mmu \
helper_atomic_fetch_addw_le_mmu \
helper_atomic_fetch_andw_le_mmu \
helper_atomic_fetch_orw_le_mmu \
helper_atomic_fetch_xorw_le_mmu \
helper_atomic_add_fetchw_le_mmu \
helper_atomic_and_fetchw_le_mmu \
helper_atomic_or_fetchw_le_mmu \
helper_atomic_xor_fetchw_le_mmu \
helper_atomic_fetch_sminw_le_mmu \
helper_atomic_fetch_uminw_le_mmu \
helper_atomic_fetch_smaxw_le_mmu \
helper_atomic_fetch_umaxw_le_mmu \
helper_atomic_smin_fetchw_le_mmu \
helper_atomic_umin_fetchw_le_mmu \
helper_atomic_smax_fetchw_le_mmu \
helper_atomic_umax_fetchw_le_mmu \
helper_atomic_cmpxchgw_be_mmu \
helper_atomic_xchgw_be_mmu \
helper_atomic_fetch_andw_be_mmu \
helper_atomic_fetch_orw_be_mmu \
helper_atomic_fetch_xorw_be_mmu \
helper_atomic_and_fetchw_be_mmu \
helper_atomic_or_fetchw_be_mmu \
helper_atomic_xor_fetchw_be_mmu \
helper_atomic_fetch_sminw_be_mmu \
helper_atomic_fetch_uminw_be_mmu \
helper_atomic_fetch_smaxw_be_mmu \
helper_atomic_fetch_umaxw_be_mmu \
helper_atomic_smin_fetchw_be_mmu \
helper_atomic_umin_fetchw_be_mmu \
helper_atomic_smax_fetchw_be_mmu \
helper_atomic_umax_fetchw_be_mmu \
helper_atomic_fetch_addw_be_mmu \
helper_atomic_add_fetchw_be_mmu \
helper_atomic_cmpxchgl_le_mmu \
helper_atomic_xchgl_le_mmu \
helper_atomic_fetch_addl_le_mmu \
helper_atomic_fetch_andl_le_mmu \
helper_atomic_fetch_orl_le_mmu \
helper_atomic_fetch_xorl_le_mmu \
helper_atomic_add_fetchl_le_mmu \
helper_atomic_and_fetchl_le_mmu \
helper_atomic_or_fetchl_le_mmu \
helper_atomic_xor_fetchl_le_mmu \
helper_atomic_fetch_sminl_le_mmu \
helper_atomic_fetch_uminl_le_mmu \
helper_atomic_fetch_smaxl_le_mmu \
helper_atomic_fetch_umaxl_le_mmu \
helper_atomic_smin_fetchl_le_mmu \
helper_atomic_umin_fetchl_le_mmu \
helper_atomic_smax_fetchl_le_mmu \
helper_atomic_umax_fetchl_le_mmu \
helper_atomic_cmpxchgl_be_mmu \
helper_atomic_xchgl_be_mmu \
helper_atomic_fetch_andl_be_mmu \
helper_atomic_fetch_orl_be_mmu \
helper_atomic_fetch_xorl_be_mmu \
helper_atomic_and_fetchl_be_mmu \
helper_atomic_or_fetchl_be_mmu \
helper_atomic_xor_fetchl_be_mmu \
helper_atomic_fetch_sminl_be_mmu \
helper_atomic_fetch_uminl_be_mmu \
helper_atomic_fetch_smaxl_be_mmu \
helper_atomic_fetch_umaxl_be_mmu \
helper_atomic_smin_fetchl_be_mmu \
helper_atomic_umin_fetchl_be_mmu \
helper_atomic_smax_fetchl_be_mmu \
helper_atomic_umax_fetchl_be_mmu \
helper_atomic_fetch_addl_be_mmu \
helper_atomic_add_fetchl_be_mmu \
helper_atomic_cmpxchgq_le_mmu \
helper_atomic_xchgq_le_mmu \
helper_atomic_fetch_addq_le_mmu \
helper_atomic_fetch_andq_le_mmu \
helper_atomic_fetch_orq_le_mmu \
helper_atomic_fetch_xorq_le_mmu \
helper_atomic_add_fetchq_le_mmu \
helper_atomic_and_fetchq_le_mmu \
helper_atomic_or_fetchq_le_mmu \
helper_atomic_xor_fetchq_le_mmu \
helper_atomic_fetch_sminq_le_mmu \
helper_atomic_fetch_uminq_le_mmu \
helper_atomic_fetch_smaxq_le_mmu \
helper_atomic_fetch_umaxq_le_mmu \
helper_atomic_smin_fetchq_le_mmu \
helper_atomic_umin_fetchq_le_mmu \
helper_atomic_smax_fetchq_le_mmu \
helper_atomic_umax_fetchq_le_mmu \
helper_atomic_cmpxchgq_be_mmu \
helper_atomic_xchgq_be_mmu \
helper_atomic_fetch_andq_be_mmu \
helper_atomic_fetch_orq_be_mmu \
helper_atomic_fetch_xorq_be_mmu \
helper_atomic_and_fetchq_be_mmu \
helper_atomic_or_fetchq_be_mmu \
helper_atomic_xor_fetchq_be_mmu \
helper_atomic_fetch_sminq_be_mmu \
helper_atomic_fetch_uminq_be_mmu \
helper_atomic_fetch_smaxq_be_mmu \
helper_atomic_fetch_umaxq_be_mmu \
helper_atomic_smin_fetchq_be_mmu \
helper_atomic_umin_fetchq_be_mmu \
helper_atomic_smax_fetchq_be_mmu \
helper_atomic_umax_fetchq_be_mmu \
helper_atomic_fetch_addq_be_mmu \
helper_atomic_add_fetchq_be_mmu \
helper_atomic_cmpxchgb \
helper_atomic_xchgb \
helper_atomic_fetch_addb \
helper_atomic_fetch_andb \
helper_atomic_fetch_orb \
helper_atomic_fetch_xorb \
helper_atomic_add_fetchb \
helper_atomic_and_fetchb \
helper_atomic_or_fetchb \
helper_atomic_xor_fetchb \
helper_atomic_fetch_sminb \
helper_atomic_fetch_uminb \
helper_atomic_fetch_smaxb \
helper_atomic_fetch_umaxb \
helper_atomic_smin_fetchb \
helper_atomic_umin_fetchb \
helper_atomic_smax_fetchb \
helper_atomic_umax_fetchb \
helper_atomic_cmpxchgw_le \
helper_atomic_xchgw_le \
helper_atomic_fetch_addw_le \
helper_atomic_fetch_andw_le \
helper_atomic_fetch_orw_le \
helper_atomic_fetch_xorw_le \
helper_atomic_add_fetchw_le \
helper_atomic_and_fetchw_le \
helper_atomic_or_fetchw_le \
helper_atomic_xor_fetchw_le \
helper_atomic_fetch_sminw_le \
helper_atomic_fetch_uminw_le \
helper_atomic_fetch_smaxw_le \
helper_atomic_fetch_umaxw_le \
helper_atomic_smin_fetchw_le \
helper_atomic_umin_fetchw_le \
helper_atomic_smax_fetchw_le \
helper_atomic_umax_fetchw_le \
helper_atomic_cmpxchgw_be \
helper_atomic_xchgw_be \
helper_atomic_fetch_andw_be \
helper_atomic_fetch_orw_be \
helper_atomic_fetch_xorw_be \
helper_atomic_and_fetchw_be \
helper_atomic_or_fetchw_be \
helper_atomic_xor_fetchw_be \
helper_atomic_fetch_sminw_be \
helper_atomic_fetch_uminw_be \
helper_atomic_fetch_smaxw_be \
helper_atomic_fetch_umaxw_be \
helper_atomic_smin_fetchw_be \
helper_atomic_umin_fetchw_be \
helper_atomic_smax_fetchw_be \
helper_atomic_umax_fetchw_be \
helper_atomic_fetch_addw_be \
helper_atomic_add_fetchw_be \
helper_atomic_cmpxchgl_le \
helper_atomic_xchgl_le \
helper_atomic_fetch_addl_le \
helper_atomic_fetch_andl_le \
helper_atomic_fetch_orl_le \
helper_atomic_fetch_xorl_le \
helper_atomic_add_fetchl_le \
helper_atomic_and_fetchl_le \
helper_atomic_or_fetchl_le \
helper_atomic_xor_fetchl_le \
helper_atomic_fetch_sminl_le \
helper_atomic_fetch_uminl_le \
helper_atomic_fetch_smaxl_le \
helper_atomic_fetch_umaxl_le \
helper_atomic_smin_fetchl_le \
helper_atomic_umin_fetchl_le \
helper_atomic_smax_fetchl_le \
helper_atomic_umax_fetchl_le \
helper_atomic_cmpxchgl_be \
helper_atomic_xchgl_be \
helper_atomic_fetch_andl_be \
helper_atomic_fetch_orl_be \
helper_atomic_fetch_xorl_be \
helper_atomic_and_fetchl_be \
helper_atomic_or_fetchl_be \
helper_atomic_xor_fetchl_be \
helper_atomic_fetch_sminl_be \
helper_atomic_fetch_uminl_be \
helper_atomic_fetch_smaxl_be \
helper_atomic_fetch_umaxl_be \
helper_atomic_smin_fetchl_be \
helper_atomic_umin_fetchl_be \
helper_atomic_smax_fetchl_be \
helper_atomic_umax_fetchl_be \
helper_atomic_fetch_addl_be \
helper_atomic_add_fetchl_be \
helper_atomic_cmpxchgq_le \
helper_atomic_xchgq_le \
helper_atomic_fetch_addq_le \
helper_atomic_fetch_andq_le \
helper_atomic_fetch_orq_le \
helper_atomic_fetch_xorq_le \
helper_atomic_add_fetchq_le \
helper_atomic_and_fetchq_le \
helper_atomic_or_fetchq_le \
helper_atomic_xor_fetchq_le \
helper_atomic_fetch_sminq_le \
helper_atomic_fetch_uminq_le \
helper_atomic_fetch_smaxq_le \
helper_atomic_fetch_umaxq_le \
helper_atomic_smin_fetchq_le \
helper_atomic_umin_fetchq_le \
helper_atomic_smax_fetchq_le \
helper_atomic_umax_fetchq_le \
helper_atomic_cmpxchgq_be \
helper_atomic_xchgq_be \
helper_atomic_fetch_andq_be \
helper_atomic_fetch_orq_be \
helper_atomic_fetch_xorq_be \
helper_atomic_and_fetchq_be \
helper_atomic_or_fetchq_be \
helper_atomic_xor_fetchq_be \
helper_atomic_fetch_sminq_be \
helper_atomic_fetch_uminq_be \
helper_atomic_fetch_smaxq_be \
helper_atomic_fetch_umaxq_be \
helper_atomic_smin_fetchq_be \
helper_atomic_umin_fetchq_be \
helper_atomic_smax_fetchq_be \
helper_atomic_umax_fetchq_be \
helper_atomic_fetch_addq_be \
helper_atomic_add_fetchq_be \
cpu_ldub_code \
cpu_lduw_code \
cpu_ldl_code \
cpu_ldq_code \
helper_div_i32 \
helper_rem_i32 \
helper_divu_i32 \
helper_remu_i32 \
helper_shl_i64 \
helper_shr_i64 \
helper_sar_i64 \
helper_div_i64 \
helper_rem_i64 \
helper_divu_i64 \
helper_remu_i64 \
helper_muluh_i64 \
helper_mulsh_i64 \
helper_clz_i32 \
helper_ctz_i32 \
helper_clz_i64 \
helper_ctz_i64 \
helper_clrsb_i32 \
helper_clrsb_i64 \
helper_ctpop_i32 \
helper_ctpop_i64 \
helper_lookup_tb_ptr \
helper_exit_atomic \
helper_gvec_add8 \
helper_gvec_add16 \
helper_gvec_add32 \
helper_gvec_add64 \
helper_gvec_adds8 \
helper_gvec_adds16 \
helper_gvec_adds32 \
helper_gvec_adds64 \
helper_gvec_sub8 \
helper_gvec_sub16 \
helper_gvec_sub32 \
helper_gvec_sub64 \
helper_gvec_subs8 \
helper_gvec_subs16 \
helper_gvec_subs32 \
helper_gvec_subs64 \
helper_gvec_mul8 \
helper_gvec_mul16 \
helper_gvec_mul32 \
helper_gvec_mul64 \
helper_gvec_muls8 \
helper_gvec_muls16 \
helper_gvec_muls32 \
helper_gvec_muls64 \
helper_gvec_neg8 \
helper_gvec_neg16 \
helper_gvec_neg32 \
helper_gvec_neg64 \
helper_gvec_abs8 \
helper_gvec_abs16 \
helper_gvec_abs32 \
helper_gvec_abs64 \
helper_gvec_mov \
helper_gvec_dup64 \
helper_gvec_dup32 \
helper_gvec_dup16 \
helper_gvec_dup8 \
helper_gvec_not \
helper_gvec_and \
helper_gvec_or \
helper_gvec_xor \
helper_gvec_andc \
helper_gvec_orc \
helper_gvec_nand \
helper_gvec_nor \
helper_gvec_eqv \
helper_gvec_ands \
helper_gvec_xors \
helper_gvec_ors \
helper_gvec_shl8i \
helper_gvec_shl16i \
helper_gvec_shl32i \
helper_gvec_shl64i \
helper_gvec_shr8i \
helper_gvec_shr16i \
helper_gvec_shr32i \
helper_gvec_shr64i \
helper_gvec_sar8i \
helper_gvec_sar16i \
helper_gvec_sar32i \
helper_gvec_sar64i \
helper_gvec_shl8v \
helper_gvec_shl16v \
helper_gvec_shl32v \
helper_gvec_shl64v \
helper_gvec_shr8v \
helper_gvec_shr16v \
helper_gvec_shr32v \
helper_gvec_shr64v \
helper_gvec_sar8v \
helper_gvec_sar16v \
helper_gvec_sar32v \
helper_gvec_sar64v \
helper_gvec_eq8 \
helper_gvec_ne8 \
helper_gvec_lt8 \
helper_gvec_le8 \
helper_gvec_ltu8 \
helper_gvec_leu8 \
helper_gvec_eq16 \
helper_gvec_ne16 \
helper_gvec_lt16 \
helper_gvec_le16 \
helper_gvec_ltu16 \
helper_gvec_leu16 \
helper_gvec_eq32 \
helper_gvec_ne32 \
helper_gvec_lt32 \
helper_gvec_le32 \
helper_gvec_ltu32 \
helper_gvec_leu32 \
helper_gvec_eq64 \
helper_gvec_ne64 \
helper_gvec_lt64 \
helper_gvec_le64 \
helper_gvec_ltu64 \
helper_gvec_leu64 \
helper_gvec_ssadd8 \
helper_gvec_ssadd16 \
helper_gvec_ssadd32 \
helper_gvec_ssadd64 \
helper_gvec_sssub8 \
helper_gvec_sssub16 \
helper_gvec_sssub32 \
helper_gvec_sssub64 \
helper_gvec_usadd8 \
helper_gvec_usadd16 \
helper_gvec_usadd32 \
helper_gvec_usadd64 \
helper_gvec_ussub8 \
helper_gvec_ussub16 \
helper_gvec_ussub32 \
helper_gvec_ussub64 \
helper_gvec_smin8 \
helper_gvec_smin16 \
helper_gvec_smin32 \
helper_gvec_smin64 \
helper_gvec_smax8 \
helper_gvec_smax16 \
helper_gvec_smax32 \
helper_gvec_smax64 \
helper_gvec_umin8 \
helper_gvec_umin16 \
helper_gvec_umin32 \
helper_gvec_umin64 \
helper_gvec_umax8 \
helper_gvec_umax16 \
helper_gvec_umax32 \
helper_gvec_umax64 \
helper_gvec_bitsel \
cpu_restore_state \
page_collection_lock \
page_collection_unlock \
free_code_gen_buffer \
tcg_exec_init \
tb_cleanup \
tb_flush \
tb_phys_invalidate \
tb_gen_code \
tb_exec_lock \
tb_exec_unlock \
tb_invalidate_phys_page_range \
tb_invalidate_phys_range \
tb_invalidate_phys_page_fast \
tb_check_watchpoint \
cpu_io_recompile \
tb_flush_jmp_cache \
tcg_flush_softmmu_tlb \
translator_loop_temp_check \
translator_loop \
helper_atomic_cmpxchgo_le_mmu \
helper_atomic_cmpxchgo_be_mmu \
helper_atomic_ldo_le_mmu \
helper_atomic_ldo_be_mmu \
helper_atomic_sto_le_mmu \
helper_atomic_sto_be_mmu \
unassigned_mem_ops \
floatx80_infinity \
dup_const_func \
gen_helper_raise_exception \
gen_helper_raise_interrupt \
gen_helper_vfp_get_fpscr \
gen_helper_vfp_set_fpscr \
gen_helper_cpsr_read \
gen_helper_cpsr_write \
"

x86_64_SYMBOLS="
cpu_get_tsc \
x86_cpu_get_memory_mapping \
cpu_x86_update_dr7 \
breakpoint_handler \
helper_single_step \
helper_rechecking_single_step \
helper_set_dr \
helper_get_dr \
helper_bpt_io \
helper_cc_compute_all \
cpu_cc_compute_all \
helper_cc_compute_c \
helper_write_eflags \
helper_read_eflags \
helper_clts \
helper_reset_rf \
helper_cli \
helper_sti \
helper_clac \
helper_stac \
get_register_name_32 \
host_cpuid \
host_vendor_fms \
x86_cpu_set_default_version \
cpu_clear_apic_feature \
cpu_x86_cpuid \
x86_cpu_pending_interrupt \
x86_update_hflags \
cpu_x86_init \
helper_raise_interrupt \
helper_raise_exception \
raise_interrupt \
raise_exception_err \
raise_exception_err_ra \
raise_exception \
raise_exception_ra \
x86_cpu_tlb_fill \
cpu_set_ignne \
helper_flds_FT0 \
helper_fldl_FT0 \
helper_fildl_FT0 \
helper_flds_ST0 \
helper_fldl_ST0 \
helper_fildl_ST0 \
helper_fildll_ST0 \
helper_fsts_ST0 \
helper_fstl_ST0 \
helper_fist_ST0 \
helper_fistl_ST0 \
helper_fistll_ST0 \
helper_fistt_ST0 \
helper_fisttl_ST0 \
helper_fisttll_ST0 \
helper_fldt_ST0 \
helper_fstt_ST0 \
helper_fpush \
helper_fpop \
helper_fdecstp \
helper_fincstp \
helper_ffree_STN \
helper_fmov_ST0_FT0 \
helper_fmov_FT0_STN \
helper_fmov_ST0_STN \
helper_fmov_STN_ST0 \
helper_fxchg_ST0_STN \
helper_fcom_ST0_FT0 \
helper_fucom_ST0_FT0 \
helper_fcomi_ST0_FT0 \
helper_fucomi_ST0_FT0 \
helper_fadd_ST0_FT0 \
helper_fmul_ST0_FT0 \
helper_fsub_ST0_FT0 \
helper_fsubr_ST0_FT0 \
helper_fdiv_ST0_FT0 \
helper_fdivr_ST0_FT0 \
helper_fadd_STN_ST0 \
helper_fmul_STN_ST0 \
helper_fsub_STN_ST0 \
helper_fsubr_STN_ST0 \
helper_fdiv_STN_ST0 \
helper_fdivr_STN_ST0 \
helper_fchs_ST0 \
helper_fabs_ST0 \
helper_fld1_ST0 \
helper_fldl2t_ST0 \
helper_fldl2e_ST0 \
helper_fldpi_ST0 \
helper_fldlg2_ST0 \
helper_fldln2_ST0 \
helper_fldz_ST0 \
helper_fldz_FT0 \
helper_fnstsw \
helper_fnstcw \
update_fp_status \
helper_fldcw \
helper_fclex \
helper_fwait \
helper_fninit \
helper_fbld_ST0 \
helper_fbst_ST0 \
helper_f2xm1 \
helper_fyl2x \
helper_fptan \
helper_fpatan \
helper_fxtract \
helper_fprem1 \
helper_fprem \
helper_fyl2xp1 \
helper_fsqrt \
helper_fsincos \
helper_frndint \
helper_fscale \
helper_fsin \
helper_fcos \
helper_fxam_ST0 \
helper_fstenv \
helper_fldenv \
helper_fsave \
helper_frstor \
helper_fxsave \
helper_xsave \
helper_xsaveopt \
helper_fxrstor \
helper_xrstor \
helper_xgetbv \
helper_xsetbv \
update_mxcsr_status \
helper_ldmxcsr \
helper_enter_mmx \
helper_emms \
helper_movq \
helper_psrlw_mmx \
helper_psraw_mmx \
helper_psllw_mmx \
helper_psrld_mmx \
helper_psrad_mmx \
helper_pslld_mmx \
helper_psrlq_mmx \
helper_psllq_mmx \
helper_paddb_mmx \
helper_paddw_mmx \
helper_paddl_mmx \
helper_paddq_mmx \
helper_psubb_mmx \
helper_psubw_mmx \
helper_psubl_mmx \
helper_psubq_mmx \
helper_paddusb_mmx \
helper_paddsb_mmx \
helper_psubusb_mmx \
helper_psubsb_mmx \
helper_paddusw_mmx \
helper_paddsw_mmx \
helper_psubusw_mmx \
helper_psubsw_mmx \
helper_pminub_mmx \
helper_pmaxub_mmx \
helper_pminsw_mmx \
helper_pmaxsw_mmx \
helper_pand_mmx \
helper_pandn_mmx \
helper_por_mmx \
helper_pxor_mmx \
helper_pcmpgtb_mmx \
helper_pcmpgtw_mmx \
helper_pcmpgtl_mmx \
helper_pcmpeqb_mmx \
helper_pcmpeqw_mmx \
helper_pcmpeql_mmx \
helper_pmullw_mmx \
helper_pmulhrw_mmx \
helper_pmulhuw_mmx \
helper_pmulhw_mmx \
helper_pavgb_mmx \
helper_pavgw_mmx \
helper_pmuludq_mmx \
helper_pmaddwd_mmx \
helper_psadbw_mmx \
helper_maskmov_mmx \
helper_movl_mm_T0_mmx \
helper_movq_mm_T0_mmx \
helper_pshufw_mmx \
helper_pmovmskb_mmx \
helper_packsswb_mmx \
helper_packuswb_mmx \
helper_packssdw_mmx \
helper_punpcklbw_mmx \
helper_punpcklwd_mmx \
helper_punpckldq_mmx \
helper_punpckhbw_mmx \
helper_punpckhwd_mmx \
helper_punpckhdq_mmx \
helper_pi2fd \
helper_pi2fw \
helper_pf2id \
helper_pf2iw \
helper_pfacc \
helper_pfadd \
helper_pfcmpeq \
helper_pfcmpge \
helper_pfcmpgt \
helper_pfmax \
helper_pfmin \
helper_pfmul \
helper_pfnacc \
helper_pfpnacc \
helper_pfrcp \
helper_pfrsqrt \
helper_pfsub \
helper_pfsubr \
helper_pswapd \
helper_pshufb_mmx \
helper_phaddw_mmx \
helper_phaddd_mmx \
helper_phaddsw_mmx \
helper_pmaddubsw_mmx \
helper_phsubw_mmx \
helper_phsubd_mmx \
helper_phsubsw_mmx \
helper_pabsb_mmx \
helper_pabsw_mmx \
helper_pabsd_mmx \
helper_pmulhrsw_mmx \
helper_psignb_mmx \
helper_psignw_mmx \
helper_psignd_mmx \
helper_palignr_mmx \
helper_psrlw_xmm \
helper_psraw_xmm \
helper_psllw_xmm \
helper_psrld_xmm \
helper_psrad_xmm \
helper_pslld_xmm \
helper_psrlq_xmm \
helper_psllq_xmm \
helper_psrldq_xmm \
helper_pslldq_xmm \
helper_paddb_xmm \
helper_paddw_xmm \
helper_paddl_xmm \
helper_paddq_xmm \
helper_psubb_xmm \
helper_psubw_xmm \
helper_psubl_xmm \
helper_psubq_xmm \
helper_paddusb_xmm \
helper_paddsb_xmm \
helper_psubusb_xmm \
helper_psubsb_xmm \
helper_paddusw_xmm \
helper_paddsw_xmm \
helper_psubusw_xmm \
helper_psubsw_xmm \
helper_pminub_xmm \
helper_pmaxub_xmm \
helper_pminsw_xmm \
helper_pmaxsw_xmm \
helper_pand_xmm \
helper_pandn_xmm \
helper_por_xmm \
helper_pxor_xmm \
helper_pcmpgtb_xmm \
helper_pcmpgtw_xmm \
helper_pcmpgtl_xmm \
helper_pcmpeqb_xmm \
helper_pcmpeqw_xmm \
helper_pcmpeql_xmm \
helper_pmullw_xmm \
helper_pmulhuw_xmm \
helper_pmulhw_xmm \
helper_pavgb_xmm \
helper_pavgw_xmm \
helper_pmuludq_xmm \
helper_pmaddwd_xmm \
helper_psadbw_xmm \
helper_maskmov_xmm \
helper_movl_mm_T0_xmm \
helper_movq_mm_T0_xmm \
helper_shufps \
helper_shufpd \
helper_pshufd_xmm \
helper_pshuflw_xmm \
helper_pshufhw_xmm \
helper_addps \
helper_addss \
helper_addpd \
helper_addsd \
helper_subps \
helper_subss \
helper_subpd \
helper_subsd \
helper_mulps \
helper_mulss \
helper_mulpd \
helper_mulsd \
helper_divps \
helper_divss \
helper_divpd \
helper_divsd \
helper_minps \
helper_minss \
helper_minpd \
helper_minsd \
helper_maxps \
helper_maxss \
helper_maxpd \
helper_maxsd \
helper_sqrtps \
helper_sqrtss \
helper_sqrtpd \
helper_sqrtsd \
helper_cvtps2pd \
helper_cvtpd2ps \
helper_cvtss2sd \
helper_cvtsd2ss \
helper_cvtdq2ps \
helper_cvtdq2pd \
helper_cvtpi2ps \
helper_cvtpi2pd \
helper_cvtsi2ss \
helper_cvtsi2sd \
helper_cvtsq2ss \
helper_cvtsq2sd \
helper_cvtps2dq \
helper_cvtpd2dq \
helper_cvtps2pi \
helper_cvtpd2pi \
helper_cvtss2si \
helper_cvtsd2si \
helper_cvtss2sq \
helper_cvtsd2sq \
helper_cvttps2dq \
helper_cvttpd2dq \
helper_cvttps2pi \
helper_cvttpd2pi \
helper_cvttss2si \
helper_cvttsd2si \
helper_cvttss2sq \
helper_cvttsd2sq \
helper_rsqrtps \
helper_rsqrtss \
helper_rcpps \
helper_rcpss \
helper_extrq_r \
helper_extrq_i \
helper_insertq_r \
helper_insertq_i \
helper_haddps \
helper_haddpd \
helper_hsubps \
helper_hsubpd \
helper_addsubps \
helper_addsubpd \
helper_cmpeqps \
helper_cmpeqss \
helper_cmpeqpd \
helper_cmpeqsd \
helper_cmpltps \
helper_cmpltss \
helper_cmpltpd \
helper_cmpltsd \
helper_cmpleps \
helper_cmpless \
helper_cmplepd \
helper_cmplesd \
helper_cmpunordps \
helper_cmpunordss \
helper_cmpunordpd \
helper_cmpunordsd \
helper_cmpneqps \
helper_cmpneqss \
helper_cmpneqpd \
helper_cmpneqsd \
helper_cmpnltps \
helper_cmpnltss \
helper_cmpnltpd \
helper_cmpnltsd \
helper_cmpnleps \
helper_cmpnless \
helper_cmpnlepd \
helper_cmpnlesd \
helper_cmpordps \
helper_cmpordss \
helper_cmpordpd \
helper_cmpordsd \
helper_ucomiss \
helper_comiss \
helper_ucomisd \
helper_comisd \
helper_movmskps \
helper_movmskpd \
helper_pmovmskb_xmm \
helper_packsswb_xmm \
helper_packuswb_xmm \
helper_packssdw_xmm \
helper_punpcklbw_xmm \
helper_punpcklwd_xmm \
helper_punpckldq_xmm \
helper_punpcklqdq_xmm \
helper_punpckhbw_xmm \
helper_punpckhwd_xmm \
helper_punpckhdq_xmm \
helper_punpckhqdq_xmm \
helper_pshufb_xmm \
helper_phaddw_xmm \
helper_phaddd_xmm \
helper_phaddsw_xmm \
helper_pmaddubsw_xmm \
helper_phsubw_xmm \
helper_phsubd_xmm \
helper_phsubsw_xmm \
helper_pabsb_xmm \
helper_pabsw_xmm \
helper_pabsd_xmm \
helper_pmulhrsw_xmm \
helper_psignb_xmm \
helper_psignw_xmm \
helper_psignd_xmm \
helper_palignr_xmm \
helper_pblendvb_xmm \
helper_blendvps_xmm \
helper_blendvpd_xmm \
helper_ptest_xmm \
helper_pmovsxbw_xmm \
helper_pmovsxbd_xmm \
helper_pmovsxbq_xmm \
helper_pmovsxwd_xmm \
helper_pmovsxwq_xmm \
helper_pmovsxdq_xmm \
helper_pmovzxbw_xmm \
helper_pmovzxbd_xmm \
helper_pmovzxbq_xmm \
helper_pmovzxwd_xmm \
helper_pmovzxwq_xmm \
helper_pmovzxdq_xmm \
helper_pmuldq_xmm \
helper_pcmpeqq_xmm \
helper_packusdw_xmm \
helper_pminsb_xmm \
helper_pminsd_xmm \
helper_pminuw_xmm \
helper_pminud_xmm \
helper_pmaxsb_xmm \
helper_pmaxsd_xmm \
helper_pmaxuw_xmm \
helper_pmaxud_xmm \
helper_pmulld_xmm \
helper_phminposuw_xmm \
helper_roundps_xmm \
helper_roundpd_xmm \
helper_roundss_xmm \
helper_roundsd_xmm \
helper_blendps_xmm \
helper_blendpd_xmm \
helper_pblendw_xmm \
helper_dpps_xmm \
helper_dppd_xmm \
helper_mpsadbw_xmm \
helper_pcmpgtq_xmm \
helper_pcmpestri_xmm \
helper_pcmpestrm_xmm \
helper_pcmpistri_xmm \
helper_pcmpistrm_xmm \
helper_crc32 \
helper_pclmulqdq_xmm \
helper_aesdec_xmm \
helper_aesdeclast_xmm \
helper_aesenc_xmm \
helper_aesenclast_xmm \
helper_aesimc_xmm \
helper_aeskeygenassist_xmm \
cpu_sync_bndcs_hflags \
cpu_x86_support_mca_broadcast \
x86_cpu_set_a20 \
cpu_x86_update_cr0 \
cpu_x86_update_cr3 \
cpu_x86_update_cr4 \
x86_cpu_get_phys_page_attrs_debug \
cpu_x86_get_descr_debug \
do_cpu_init \
do_cpu_sipi \
x86_cpu_exec_enter \
x86_cpu_exec_exit \
x86_ldub_phys \
x86_lduw_phys \
x86_ldl_phys \
x86_ldq_phys \
x86_stb_phys \
x86_stl_phys_notdirty \
x86_stw_phys \
x86_stl_phys \
x86_stq_phys \
helper_divb_AL \
helper_idivb_AL \
helper_divw_AX \
helper_idivw_AX \
helper_divl_EAX \
helper_idivl_EAX \
helper_aam \
helper_aad \
helper_aaa \
helper_aas \
helper_daa \
helper_das \
helper_divq_EAX \
helper_idivq_EAX \
helper_pdep \
helper_pext \
helper_rclb \
helper_rcrb \
helper_rclw \
helper_rcrw \
helper_rcll \
helper_rcrl \
helper_rclq \
helper_rcrq \
helper_cr4_testbit \
helper_rdrand \
helper_cmpxchg8b_unlocked \
helper_cmpxchg8b \
helper_cmpxchg16b_unlocked \
helper_cmpxchg16b \
helper_boundw \
helper_boundl \
helper_outb \
helper_inb \
helper_outw \
helper_inw \
helper_outl \
helper_inl \
helper_into \
helper_cpuid \
helper_read_crN \
helper_write_crN \
helper_lmsw \
helper_invlpg \
helper_rdtsc \
helper_rdtscp \
helper_rdpmc \
helper_wrmsr \
helper_rdmsr \
helper_hlt \
helper_monitor \
helper_mwait \
helper_pause \
helper_debug \
helper_rdpkru \
helper_wrpkru \
helper_bndck \
helper_bndldx64 \
helper_bndldx32 \
helper_bndstx64 \
helper_bndstx32 \
helper_bnd_jmp \
helper_syscall \
helper_sysret \
x86_cpu_do_interrupt \
do_interrupt_x86_hardirq \
x86_cpu_exec_interrupt \
helper_lldt \
helper_ltr \
uc_check_cpu_x86_load_seg \
helper_load_seg \
helper_ljmp_protected \
helper_lcall_real \
helper_lcall_protected \
helper_iret_real \
helper_iret_protected \
helper_lret_protected \
helper_sysenter \
helper_sysexit \
helper_lsl \
helper_lar \
helper_verr \
helper_verw \
cpu_x86_load_seg \
helper_check_iob \
helper_check_iow \
helper_check_iol \
do_smm_enter \
helper_rsm \
helper_vmrun \
helper_vmmcall \
helper_vmload \
helper_vmsave \
helper_stgi \
helper_clgi \
helper_skinit \
helper_invlpga \
cpu_svm_check_intercept_param \
helper_svm_check_intercept_param \
helper_svm_check_io \
cpu_vmexit \
do_vmexit \
tcg_x86_init \
gen_intermediate_code \
restore_state_to_opc \
x86_cpu_xsave_all_areas \
x86_cpu_xrstor_all_areas \
cpu_get_fp80 \
cpu_set_fp80 \
x86_reg_reset \
x86_reg_read \
x86_reg_write \
"

arm_SYMBOLS="
arm_cpu_exec_interrupt \
arm_cpu_update_virq \
arm_cpu_update_vfiq \
arm_cpu_initfn \
gt_cntfrq_period_ns \
arm_cpu_post_init \
arm_cpu_realizefn \
a15_l2ctlr_read \
arm_cpu_class_init \
cpu_arm_init \
helper_crypto_aese \
helper_crypto_aesmc \
helper_crypto_sha1_3reg \
helper_crypto_sha1h \
helper_crypto_sha1su1 \
helper_crypto_sha256h \
helper_crypto_sha256h2 \
helper_crypto_sha256su0 \
helper_crypto_sha256su1 \
helper_crypto_sha512h \
helper_crypto_sha512h2 \
helper_crypto_sha512su0 \
helper_crypto_sha512su1 \
helper_crypto_sm3partw1 \
helper_crypto_sm3partw2 \
helper_crypto_sm3tt \
helper_crypto_sm4e \
helper_crypto_sm4ekey \
helper_check_breakpoints \
arm_debug_check_watchpoint \
arm_debug_excp_handler \
arm_adjust_watchpoint_address \
read_raw_cp_reg \
pmu_init \
pmu_op_start \
pmu_op_finish \
pmu_pre_el_change \
pmu_post_el_change \
arm_pmu_timer_cb \
arm_gt_ptimer_cb \
arm_gt_vtimer_cb \
arm_gt_htimer_cb \
arm_gt_stimer_cb \
arm_gt_hvtimer_cb \
arm_hcr_el2_eff \
sve_exception_el \
sve_zcr_len_for_el \
hw_watchpoint_update \
hw_watchpoint_update_all \
hw_breakpoint_update \
hw_breakpoint_update_all \
register_cp_regs_for_features \
define_one_arm_cp_reg_with_opaque \
define_arm_cp_regs_with_opaque \
modify_arm_cp_regs \
get_arm_cp_reginfo \
arm_cp_write_ignore \
arm_cp_read_zero \
arm_cp_reset_ignore \
cpsr_read \
cpsr_write \
helper_sxtb16 \
helper_uxtb16 \
helper_sdiv \
helper_udiv \
helper_rbit \
arm_phys_excp_target_el \
aarch64_sync_32_to_64 \
aarch64_sync_64_to_32 \
arm_cpu_do_interrupt \
arm_sctlr \
arm_s1_regime_using_lpae_format \
aa64_va_parameters \
v8m_security_lookup \
pmsav8_mpu_lookup \
get_phys_addr \
arm_cpu_get_phys_page_attrs_debug \
helper_qadd16 \
helper_qadd8 \
helper_qsub16 \
helper_qsub8 \
helper_qsubaddx \
helper_qaddsubx \
helper_uqadd16 \
helper_uqadd8 \
helper_uqsub16 \
helper_uqsub8 \
helper_uqsubaddx \
helper_uqaddsubx \
helper_sadd16 \
helper_sadd8 \
helper_ssub16 \
helper_ssub8 \
helper_ssubaddx \
helper_saddsubx \
helper_uadd16 \
helper_uadd8 \
helper_usub16 \
helper_usub8 \
helper_usubaddx \
helper_uaddsubx \
helper_shadd16 \
helper_shadd8 \
helper_shsub16 \
helper_shsub8 \
helper_shsubaddx \
helper_shaddsubx \
helper_uhadd16 \
helper_uhadd8 \
helper_uhsub16 \
helper_uhsub8 \
helper_uhsubaddx \
helper_uhaddsubx \
helper_usad8 \
helper_sel_flags \
helper_crc32 \
helper_crc32c \
fp_exception_el \
arm_mmu_idx_to_el \
arm_mmu_idx_el \
arm_mmu_idx \
arm_stage1_mmu_idx \
arm_rebuild_hflags \
helper_rebuild_hflags_m32_newel \
helper_rebuild_hflags_m32 \
helper_rebuild_hflags_a32_newel \
helper_rebuild_hflags_a32 \
helper_rebuild_hflags_a64 \
cpu_get_tb_cpu_state \
helper_iwmmxt_maddsq \
helper_iwmmxt_madduq \
helper_iwmmxt_sadb \
helper_iwmmxt_sadw \
helper_iwmmxt_mulslw \
helper_iwmmxt_mulshw \
helper_iwmmxt_mululw \
helper_iwmmxt_muluhw \
helper_iwmmxt_macsw \
helper_iwmmxt_macuw \
helper_iwmmxt_unpacklb \
helper_iwmmxt_unpacklw \
helper_iwmmxt_unpackll \
helper_iwmmxt_unpacklub \
helper_iwmmxt_unpackluw \
helper_iwmmxt_unpacklul \
helper_iwmmxt_unpacklsb \
helper_iwmmxt_unpacklsw \
helper_iwmmxt_unpacklsl \
helper_iwmmxt_unpackhb \
helper_iwmmxt_unpackhw \
helper_iwmmxt_unpackhl \
helper_iwmmxt_unpackhub \
helper_iwmmxt_unpackhuw \
helper_iwmmxt_unpackhul \
helper_iwmmxt_unpackhsb \
helper_iwmmxt_unpackhsw \
helper_iwmmxt_unpackhsl \
helper_iwmmxt_cmpeqb \
helper_iwmmxt_cmpeqw \
helper_iwmmxt_cmpeql \
helper_iwmmxt_cmpgtsb \
helper_iwmmxt_cmpgtsw \
helper_iwmmxt_cmpgtsl \
helper_iwmmxt_cmpgtub \
helper_iwmmxt_cmpgtuw \
helper_iwmmxt_cmpgtul \
helper_iwmmxt_minsb \
helper_iwmmxt_minsw \
helper_iwmmxt_minsl \
helper_iwmmxt_minub \
helper_iwmmxt_minuw \
helper_iwmmxt_minul \
helper_iwmmxt_maxsb \
helper_iwmmxt_maxsw \
helper_iwmmxt_maxsl \
helper_iwmmxt_maxub \
helper_iwmmxt_maxuw \
helper_iwmmxt_maxul \
helper_iwmmxt_subnb \
helper_iwmmxt_subnw \
helper_iwmmxt_subnl \
helper_iwmmxt_addnb \
helper_iwmmxt_addnw \
helper_iwmmxt_addnl \
helper_iwmmxt_subub \
helper_iwmmxt_subuw \
helper_iwmmxt_subul \
helper_iwmmxt_addub \
helper_iwmmxt_adduw \
helper_iwmmxt_addul \
helper_iwmmxt_subsb \
helper_iwmmxt_subsw \
helper_iwmmxt_subsl \
helper_iwmmxt_addsb \
helper_iwmmxt_addsw \
helper_iwmmxt_addsl \
helper_iwmmxt_avgb0 \
helper_iwmmxt_avgb1 \
helper_iwmmxt_avgw0 \
helper_iwmmxt_avgw1 \
helper_iwmmxt_align \
helper_iwmmxt_insr \
helper_iwmmxt_setpsr_nz \
helper_iwmmxt_bcstb \
helper_iwmmxt_bcstw \
helper_iwmmxt_bcstl \
helper_iwmmxt_addcb \
helper_iwmmxt_addcw \
helper_iwmmxt_addcl \
helper_iwmmxt_msbb \
helper_iwmmxt_msbw \
helper_iwmmxt_msbl \
helper_iwmmxt_srlw \
helper_iwmmxt_srll \
helper_iwmmxt_srlq \
helper_iwmmxt_sllw \
helper_iwmmxt_slll \
helper_iwmmxt_sllq \
helper_iwmmxt_sraw \
helper_iwmmxt_sral \
helper_iwmmxt_sraq \
helper_iwmmxt_rorw \
helper_iwmmxt_rorl \
helper_iwmmxt_rorq \
helper_iwmmxt_shufh \
helper_iwmmxt_packuw \
helper_iwmmxt_packul \
helper_iwmmxt_packuq \
helper_iwmmxt_packsw \
helper_iwmmxt_packsl \
helper_iwmmxt_packsq \
helper_iwmmxt_muladdsl \
helper_iwmmxt_muladdsw \
helper_iwmmxt_muladdswl \
armv7m_nvic_set_pending \
helper_v7m_preserve_fp_state \
write_v7m_exception \
helper_v7m_bxns \
helper_v7m_blxns \
armv7m_nvic_neg_prio_requested \
helper_v7m_vlstm \
helper_v7m_vlldm \
arm_v7m_cpu_do_interrupt \
helper_v7m_mrs \
helper_v7m_msr \
helper_v7m_tt \
arm_v7m_mmu_idx_all \
arm_v7m_mmu_idx_for_secstate_and_priv \
arm_v7m_mmu_idx_for_secstate \
helper_neon_qadd_u8 \
helper_neon_qadd_u16 \
helper_neon_qadd_u32 \
helper_neon_qadd_u64 \
helper_neon_qadd_s8 \
helper_neon_qadd_s16 \
helper_neon_qadd_s32 \
helper_neon_qadd_s64 \
helper_neon_uqadd_s8 \
helper_neon_uqadd_s16 \
helper_neon_uqadd_s32 \
helper_neon_uqadd_s64 \
helper_neon_sqadd_u8 \
helper_neon_sqadd_u16 \
helper_neon_sqadd_u32 \
helper_neon_sqadd_u64 \
helper_neon_qsub_u8 \
helper_neon_qsub_u16 \
helper_neon_qsub_u32 \
helper_neon_qsub_u64 \
helper_neon_qsub_s8 \
helper_neon_qsub_s16 \
helper_neon_qsub_s32 \
helper_neon_qsub_s64 \
helper_neon_hadd_s8 \
helper_neon_hadd_u8 \
helper_neon_hadd_s16 \
helper_neon_hadd_u16 \
helper_neon_hadd_s32 \
helper_neon_hadd_u32 \
helper_neon_rhadd_s8 \
helper_neon_rhadd_u8 \
helper_neon_rhadd_s16 \
helper_neon_rhadd_u16 \
helper_neon_rhadd_s32 \
helper_neon_rhadd_u32 \
helper_neon_hsub_s8 \
helper_neon_hsub_u8 \
helper_neon_hsub_s16 \
helper_neon_hsub_u16 \
helper_neon_hsub_s32 \
helper_neon_hsub_u32 \
helper_neon_cgt_s8 \
helper_neon_cgt_u8 \
helper_neon_cgt_s16 \
helper_neon_cgt_u16 \
helper_neon_cgt_s32 \
helper_neon_cgt_u32 \
helper_neon_cge_s8 \
helper_neon_cge_u8 \
helper_neon_cge_s16 \
helper_neon_cge_u16 \
helper_neon_cge_s32 \
helper_neon_cge_u32 \
helper_neon_pmin_s8 \
helper_neon_pmin_u8 \
helper_neon_pmin_s16 \
helper_neon_pmin_u16 \
helper_neon_pmax_s8 \
helper_neon_pmax_u8 \
helper_neon_pmax_s16 \
helper_neon_pmax_u16 \
helper_neon_abd_s8 \
helper_neon_abd_u8 \
helper_neon_abd_s16 \
helper_neon_abd_u16 \
helper_neon_abd_s32 \
helper_neon_abd_u32 \
helper_neon_shl_u16 \
helper_neon_shl_s16 \
helper_neon_rshl_s8 \
helper_neon_rshl_s16 \
helper_neon_rshl_s32 \
helper_neon_rshl_s64 \
helper_neon_rshl_u8 \
helper_neon_rshl_u16 \
helper_neon_rshl_u32 \
helper_neon_rshl_u64 \
helper_neon_qshl_u8 \
helper_neon_qshl_u16 \
helper_neon_qshl_u32 \
helper_neon_qshl_u64 \
helper_neon_qshl_s8 \
helper_neon_qshl_s16 \
helper_neon_qshl_s32 \
helper_neon_qshl_s64 \
helper_neon_qshlu_s8 \
helper_neon_qshlu_s16 \
helper_neon_qshlu_s32 \
helper_neon_qshlu_s64 \
helper_neon_qrshl_u8 \
helper_neon_qrshl_u16 \
helper_neon_qrshl_u32 \
helper_neon_qrshl_u64 \
helper_neon_qrshl_s8 \
helper_neon_qrshl_s16 \
helper_neon_qrshl_s32 \
helper_neon_qrshl_s64 \
helper_neon_add_u8 \
helper_neon_add_u16 \
helper_neon_padd_u8 \
helper_neon_padd_u16 \
helper_neon_sub_u8 \
helper_neon_sub_u16 \
helper_neon_mul_u8 \
helper_neon_mul_u16 \
helper_neon_tst_u8 \
helper_neon_tst_u16 \
helper_neon_tst_u32 \
helper_neon_ceq_u8 \
helper_neon_ceq_u16 \
helper_neon_ceq_u32 \
helper_neon_clz_u8 \
helper_neon_clz_u16 \
helper_neon_cls_s8 \
helper_neon_cls_s16 \
helper_neon_cls_s32 \
helper_neon_cnt_u8 \
helper_neon_rbit_u8 \
helper_neon_qdmulh_s16 \
helper_neon_qrdmulh_s16 \
helper_neon_qdmulh_s32 \
helper_neon_qrdmulh_s32 \
helper_neon_narrow_u8 \
helper_neon_narrow_u16 \
helper_neon_narrow_high_u8 \
helper_neon_narrow_high_u16 \
helper_neon_narrow_round_high_u8 \
helper_neon_narrow_round_high_u16 \
helper_neon_unarrow_sat8 \
helper_neon_narrow_sat_u8 \
helper_neon_narrow_sat_s8 \
helper_neon_unarrow_sat16 \
helper_neon_narrow_sat_u16 \
helper_neon_narrow_sat_s16 \
helper_neon_unarrow_sat32 \
helper_neon_narrow_sat_u32 \
helper_neon_narrow_sat_s32 \
helper_neon_widen_u8 \
helper_neon_widen_s8 \
helper_neon_widen_u16 \
helper_neon_widen_s16 \
helper_neon_addl_u16 \
helper_neon_addl_u32 \
helper_neon_paddl_u16 \
helper_neon_paddl_u32 \
helper_neon_subl_u16 \
helper_neon_subl_u32 \
helper_neon_addl_saturate_s32 \
helper_neon_addl_saturate_s64 \
helper_neon_abdl_u16 \
helper_neon_abdl_s16 \
helper_neon_abdl_u32 \
helper_neon_abdl_s32 \
helper_neon_abdl_u64 \
helper_neon_abdl_s64 \
helper_neon_mull_u8 \
helper_neon_mull_s8 \
helper_neon_mull_u16 \
helper_neon_mull_s16 \
helper_neon_negl_u16 \
helper_neon_negl_u32 \
helper_neon_qabs_s8 \
helper_neon_qneg_s8 \
helper_neon_qabs_s16 \
helper_neon_qneg_s16 \
helper_neon_qabs_s32 \
helper_neon_qneg_s32 \
helper_neon_qabs_s64 \
helper_neon_qneg_s64 \
helper_neon_abd_f32 \
helper_neon_ceq_f32 \
helper_neon_cge_f32 \
helper_neon_cgt_f32 \
helper_neon_acge_f32 \
helper_neon_acgt_f32 \
helper_neon_acge_f64 \
helper_neon_acgt_f64 \
helper_neon_qunzip8 \
helper_neon_qunzip16 \
helper_neon_qunzip32 \
helper_neon_unzip8 \
helper_neon_unzip16 \
helper_neon_qzip8 \
helper_neon_qzip16 \
helper_neon_qzip32 \
helper_neon_zip8 \
helper_neon_zip16 \
raise_exception \
raise_exception_ra \
helper_neon_tbl \
helper_v8m_stackcheck \
helper_add_setq \
helper_add_saturate \
helper_sub_saturate \
helper_add_usaturate \
helper_sub_usaturate \
helper_ssat \
helper_ssat16 \
helper_usat \
helper_usat16 \
helper_setend \
helper_wfi \
helper_wfe \
helper_yield \
helper_exception_internal \
helper_exception_with_syndrome \
helper_exception_bkpt_insn \
helper_cpsr_read \
helper_cpsr_write \
helper_cpsr_write_eret \
helper_get_user_reg \
helper_set_user_reg \
helper_set_r13_banked \
helper_get_r13_banked \
helper_msr_banked \
helper_mrs_banked \
helper_access_check_cp_reg \
helper_set_cp_reg \
helper_get_cp_reg \
helper_set_cp_reg64 \
helper_get_cp_reg64 \
helper_pre_hvc \
helper_pre_smc \
helper_shl_cc \
helper_shr_cc \
helper_sar_cc \
helper_ror_cc \
arm_is_psci_call \
arm_handle_psci_call \
arm_cpu_do_unaligned_access \
arm_cpu_do_transaction_failed \
arm_cpu_tlb_fill \
arm_translate_init \
arm_test_cc \
arm_free_cc \
arm_jump_cc \
arm_gen_test_cc \
vfp_expand_imm \
gen_cmtst_i64 \
gen_ushl_i32 \
gen_ushl_i64 \
gen_sshl_i32 \
gen_sshl_i64 \
gen_intermediate_code \
restore_state_to_opc \
helper_neon_qrdmlah_s16 \
helper_gvec_qrdmlah_s16 \
helper_neon_qrdmlsh_s16 \
helper_gvec_qrdmlsh_s16 \
helper_neon_qrdmlah_s32 \
helper_gvec_qrdmlah_s32 \
helper_neon_qrdmlsh_s32 \
helper_gvec_qrdmlsh_s32 \
helper_gvec_sdot_b \
helper_gvec_udot_b \
helper_gvec_sdot_h \
helper_gvec_udot_h \
helper_gvec_sdot_idx_b \
helper_gvec_udot_idx_b \
helper_gvec_sdot_idx_h \
helper_gvec_udot_idx_h \
helper_gvec_fcaddh \
helper_gvec_fcadds \
helper_gvec_fcaddd \
helper_gvec_fcmlah \
helper_gvec_fcmlah_idx \
helper_gvec_fcmlas \
helper_gvec_fcmlas_idx \
helper_gvec_fcmlad \
helper_gvec_frecpe_h \
helper_gvec_frecpe_s \
helper_gvec_frecpe_d \
helper_gvec_frsqrte_h \
helper_gvec_frsqrte_s \
helper_gvec_frsqrte_d \
helper_gvec_fadd_h \
helper_gvec_fadd_s \
helper_gvec_fadd_d \
helper_gvec_fsub_h \
helper_gvec_fsub_s \
helper_gvec_fsub_d \
helper_gvec_fmul_h \
helper_gvec_fmul_s \
helper_gvec_fmul_d \
helper_gvec_ftsmul_h \
helper_gvec_ftsmul_s \
helper_gvec_ftsmul_d \
helper_gvec_fmul_idx_h \
helper_gvec_fmul_idx_s \
helper_gvec_fmul_idx_d \
helper_gvec_fmla_idx_h \
helper_gvec_fmla_idx_s \
helper_gvec_fmla_idx_d \
helper_gvec_uqadd_b \
helper_gvec_uqadd_h \
helper_gvec_uqadd_s \
helper_gvec_sqadd_b \
helper_gvec_sqadd_h \
helper_gvec_sqadd_s \
helper_gvec_uqsub_b \
helper_gvec_uqsub_h \
helper_gvec_uqsub_s \
helper_gvec_sqsub_b \
helper_gvec_sqsub_h \
helper_gvec_sqsub_s \
helper_gvec_uqadd_d \
helper_gvec_uqsub_d \
helper_gvec_sqadd_d \
helper_gvec_sqsub_d \
helper_gvec_fmlal_a32 \
helper_gvec_fmlal_a64 \
helper_gvec_fmlal_idx_a32 \
helper_gvec_fmlal_idx_a64 \
helper_gvec_sshl_b \
helper_gvec_sshl_h \
helper_gvec_ushl_b \
helper_gvec_ushl_h \
helper_gvec_pmul_b \
helper_gvec_pmull_q \
helper_neon_pmull_h \
helper_vfp_get_fpscr \
vfp_get_fpscr \
helper_vfp_set_fpscr \
vfp_set_fpscr \
helper_vfp_adds \
helper_vfp_addd \
helper_vfp_subs \
helper_vfp_subd \
helper_vfp_muls \
helper_vfp_muld \
helper_vfp_divs \
helper_vfp_divd \
helper_vfp_mins \
helper_vfp_mind \
helper_vfp_maxs \
helper_vfp_maxd \
helper_vfp_minnums \
helper_vfp_minnumd \
helper_vfp_maxnums \
helper_vfp_maxnumd \
helper_vfp_negs \
helper_vfp_negd \
helper_vfp_abss \
helper_vfp_absd \
helper_vfp_sqrts \
helper_vfp_sqrtd \
helper_vfp_cmps \
helper_vfp_cmpes \
helper_vfp_cmpd \
helper_vfp_cmped \
helper_vfp_sitoh \
helper_vfp_tosih \
helper_vfp_tosizh \
helper_vfp_sitos \
helper_vfp_tosis \
helper_vfp_tosizs \
helper_vfp_sitod \
helper_vfp_tosid \
helper_vfp_tosizd \
helper_vfp_uitoh \
helper_vfp_touih \
helper_vfp_touizh \
helper_vfp_uitos \
helper_vfp_touis \
helper_vfp_touizs \
helper_vfp_uitod \
helper_vfp_touid \
helper_vfp_touizd \
helper_vfp_fcvtds \
helper_vfp_fcvtsd \
helper_vfp_shtod \
helper_vfp_toshd_round_to_zero \
helper_vfp_toshd \
helper_vfp_sltod \
helper_vfp_tosld_round_to_zero \
helper_vfp_tosld \
helper_vfp_sqtod \
helper_vfp_tosqd \
helper_vfp_uhtod \
helper_vfp_touhd_round_to_zero \
helper_vfp_touhd \
helper_vfp_ultod \
helper_vfp_tould_round_to_zero \
helper_vfp_tould \
helper_vfp_uqtod \
helper_vfp_touqd \
helper_vfp_shtos \
helper_vfp_toshs_round_to_zero \
helper_vfp_toshs \
helper_vfp_sltos \
helper_vfp_tosls_round_to_zero \
helper_vfp_tosls \
helper_vfp_sqtos \
helper_vfp_tosqs \
helper_vfp_uhtos \
helper_vfp_touhs_round_to_zero \
helper_vfp_touhs \
helper_vfp_ultos \
helper_vfp_touls_round_to_zero \
helper_vfp_touls \
helper_vfp_uqtos \
helper_vfp_touqs \
helper_vfp_sltoh \
helper_vfp_ultoh \
helper_vfp_sqtoh \
helper_vfp_uqtoh \
helper_vfp_toshh \
helper_vfp_touhh \
helper_vfp_toslh \
helper_vfp_toulh \
helper_vfp_tosqh \
helper_vfp_touqh \
helper_set_rmode \
helper_set_neon_rmode \
helper_vfp_fcvt_f16_to_f32 \
helper_vfp_fcvt_f32_to_f16 \
helper_vfp_fcvt_f16_to_f64 \
helper_vfp_fcvt_f64_to_f16 \
helper_recps_f32 \
helper_rsqrts_f32 \
helper_recpe_f16 \
helper_recpe_f32 \
helper_recpe_f64 \
helper_rsqrte_f16 \
helper_rsqrte_f32 \
helper_rsqrte_f64 \
helper_recpe_u32 \
helper_rsqrte_u32 \
helper_vfp_muladds \
helper_vfp_muladdd \
helper_rints_exact \
helper_rintd_exact \
helper_rints \
helper_rintd \
arm_rmode_to_sf \
helper_fjcvtzs \
helper_vjcvt \
helper_frint32_s \
helper_frint64_s \
helper_frint32_d \
helper_frint64_d \
helper_check_hcr_el2_trap \
arm_reg_reset \
arm_reg_read \
arm_reg_write \
mla_op \
mls_op \
sshl_op \
ushl_op \
uqsub_op \
sqsub_op \
uqadd_op \
sqadd_op \
sli_op \
cmtst_op \
sri_op \
usra_op \
ssra_op \
"

armeb_SYMBOLS=${arm_SYMBOLS}

aarch64_SYMBOLS="
cpu_aarch64_init \
arm_cpu_exec_interrupt \
arm_cpu_update_virq \
arm_cpu_update_vfiq \
arm_cpu_initfn \
gt_cntfrq_period_ns \
arm_cpu_post_init \
arm_cpu_realizefn \
arm_cpu_class_init \
cpu_arm_init \
helper_crypto_aese \
helper_crypto_aesmc \
helper_crypto_sha1_3reg \
helper_crypto_sha1h \
helper_crypto_sha1su1 \
helper_crypto_sha256h \
helper_crypto_sha256h2 \
helper_crypto_sha256su0 \
helper_crypto_sha256su1 \
helper_crypto_sha512h \
helper_crypto_sha512h2 \
helper_crypto_sha512su0 \
helper_crypto_sha512su1 \
helper_crypto_sm3partw1 \
helper_crypto_sm3partw2 \
helper_crypto_sm3tt \
helper_crypto_sm4e \
helper_crypto_sm4ekey \
helper_check_breakpoints \
arm_debug_check_watchpoint \
arm_debug_excp_handler \
arm_adjust_watchpoint_address \
helper_udiv64 \
helper_sdiv64 \
helper_rbit64 \
helper_msr_i_spsel \
helper_msr_i_daifset \
helper_msr_i_daifclear \
helper_vfp_cmph_a64 \
helper_vfp_cmpeh_a64 \
helper_vfp_cmps_a64 \
helper_vfp_cmpes_a64 \
helper_vfp_cmpd_a64 \
helper_vfp_cmped_a64 \
helper_vfp_mulxs \
helper_vfp_mulxd \
helper_simd_tbl \
helper_neon_ceq_f64 \
helper_neon_cge_f64 \
helper_neon_cgt_f64 \
helper_recpsf_f16 \
helper_recpsf_f32 \
helper_recpsf_f64 \
helper_rsqrtsf_f16 \
helper_rsqrtsf_f32 \
helper_rsqrtsf_f64 \
helper_neon_addlp_s8 \
helper_neon_addlp_u8 \
helper_neon_addlp_s16 \
helper_neon_addlp_u16 \
helper_frecpx_f16 \
helper_frecpx_f32 \
helper_frecpx_f64 \
helper_fcvtx_f64_to_f32 \
helper_crc32_64 \
helper_crc32c_64 \
helper_paired_cmpxchg64_le \
helper_paired_cmpxchg64_le_parallel \
helper_paired_cmpxchg64_be \
helper_paired_cmpxchg64_be_parallel \
helper_casp_le_parallel \
helper_casp_be_parallel \
helper_advsimd_addh \
helper_advsimd_subh \
helper_advsimd_mulh \
helper_advsimd_divh \
helper_advsimd_minh \
helper_advsimd_maxh \
helper_advsimd_minnumh \
helper_advsimd_maxnumh \
helper_advsimd_add2h \
helper_advsimd_sub2h \
helper_advsimd_mul2h \
helper_advsimd_div2h \
helper_advsimd_min2h \
helper_advsimd_max2h \
helper_advsimd_minnum2h \
helper_advsimd_maxnum2h \
helper_advsimd_mulxh \
helper_advsimd_mulx2h \
helper_advsimd_muladdh \
helper_advsimd_muladd2h \
helper_advsimd_ceq_f16 \
helper_advsimd_cge_f16 \
helper_advsimd_cgt_f16 \
helper_advsimd_acge_f16 \
helper_advsimd_acgt_f16 \
helper_advsimd_rinth_exact \
helper_advsimd_rinth \
helper_advsimd_f16tosinth \
helper_advsimd_f16touinth \
helper_exception_return \
helper_sqrt_f16 \
helper_dc_zva \
read_raw_cp_reg \
pmu_init \
pmu_op_start \
pmu_op_finish \
pmu_pre_el_change \
pmu_post_el_change \
arm_pmu_timer_cb \
arm_gt_ptimer_cb \
arm_gt_vtimer_cb \
arm_gt_htimer_cb \
arm_gt_stimer_cb \
arm_gt_hvtimer_cb \
arm_hcr_el2_eff \
sve_exception_el \
sve_zcr_len_for_el \
hw_watchpoint_update \
hw_watchpoint_update_all \
hw_breakpoint_update \
hw_breakpoint_update_all \
register_cp_regs_for_features \
define_one_arm_cp_reg_with_opaque \
define_arm_cp_regs_with_opaque \
modify_arm_cp_regs \
get_arm_cp_reginfo \
arm_cp_write_ignore \
arm_cp_read_zero \
arm_cp_reset_ignore \
cpsr_read \
cpsr_write \
helper_sxtb16 \
helper_uxtb16 \
helper_sdiv \
helper_udiv \
helper_rbit \
arm_phys_excp_target_el \
aarch64_sync_32_to_64 \
aarch64_sync_64_to_32 \
arm_cpu_do_interrupt \
arm_sctlr \
arm_s1_regime_using_lpae_format \
aa64_va_parameters \
v8m_security_lookup \
pmsav8_mpu_lookup \
get_phys_addr \
arm_cpu_get_phys_page_attrs_debug \
helper_qadd16 \
helper_qadd8 \
helper_qsub16 \
helper_qsub8 \
helper_qsubaddx \
helper_qaddsubx \
helper_uqadd16 \
helper_uqadd8 \
helper_uqsub16 \
helper_uqsub8 \
helper_uqsubaddx \
helper_uqaddsubx \
helper_sadd16 \
helper_sadd8 \
helper_ssub16 \
helper_ssub8 \
helper_ssubaddx \
helper_saddsubx \
helper_uadd16 \
helper_uadd8 \
helper_usub16 \
helper_usub8 \
helper_usubaddx \
helper_uaddsubx \
helper_shadd16 \
helper_shadd8 \
helper_shsub16 \
helper_shsub8 \
helper_shsubaddx \
helper_shaddsubx \
helper_uhadd16 \
helper_uhadd8 \
helper_uhsub16 \
helper_uhsub8 \
helper_uhsubaddx \
helper_uhaddsubx \
helper_usad8 \
helper_sel_flags \
helper_crc32 \
helper_crc32c \
fp_exception_el \
arm_mmu_idx_to_el \
arm_mmu_idx_el \
arm_mmu_idx \
arm_stage1_mmu_idx \
arm_rebuild_hflags \
helper_rebuild_hflags_m32_newel \
helper_rebuild_hflags_m32 \
helper_rebuild_hflags_a32_newel \
helper_rebuild_hflags_a32 \
helper_rebuild_hflags_a64 \
cpu_get_tb_cpu_state \
aarch64_sve_narrow_vq \
aarch64_sve_change_el \
helper_iwmmxt_maddsq \
helper_iwmmxt_madduq \
helper_iwmmxt_sadb \
helper_iwmmxt_sadw \
helper_iwmmxt_mulslw \
helper_iwmmxt_mulshw \
helper_iwmmxt_mululw \
helper_iwmmxt_muluhw \
helper_iwmmxt_macsw \
helper_iwmmxt_macuw \
helper_iwmmxt_unpacklb \
helper_iwmmxt_unpacklw \
helper_iwmmxt_unpackll \
helper_iwmmxt_unpacklub \
helper_iwmmxt_unpackluw \
helper_iwmmxt_unpacklul \
helper_iwmmxt_unpacklsb \
helper_iwmmxt_unpacklsw \
helper_iwmmxt_unpacklsl \
helper_iwmmxt_unpackhb \
helper_iwmmxt_unpackhw \
helper_iwmmxt_unpackhl \
helper_iwmmxt_unpackhub \
helper_iwmmxt_unpackhuw \
helper_iwmmxt_unpackhul \
helper_iwmmxt_unpackhsb \
helper_iwmmxt_unpackhsw \
helper_iwmmxt_unpackhsl \
helper_iwmmxt_cmpeqb \
helper_iwmmxt_cmpeqw \
helper_iwmmxt_cmpeql \
helper_iwmmxt_cmpgtsb \
helper_iwmmxt_cmpgtsw \
helper_iwmmxt_cmpgtsl \
helper_iwmmxt_cmpgtub \
helper_iwmmxt_cmpgtuw \
helper_iwmmxt_cmpgtul \
helper_iwmmxt_minsb \
helper_iwmmxt_minsw \
helper_iwmmxt_minsl \
helper_iwmmxt_minub \
helper_iwmmxt_minuw \
helper_iwmmxt_minul \
helper_iwmmxt_maxsb \
helper_iwmmxt_maxsw \
helper_iwmmxt_maxsl \
helper_iwmmxt_maxub \
helper_iwmmxt_maxuw \
helper_iwmmxt_maxul \
helper_iwmmxt_subnb \
helper_iwmmxt_subnw \
helper_iwmmxt_subnl \
helper_iwmmxt_addnb \
helper_iwmmxt_addnw \
helper_iwmmxt_addnl \
helper_iwmmxt_subub \
helper_iwmmxt_subuw \
helper_iwmmxt_subul \
helper_iwmmxt_addub \
helper_iwmmxt_adduw \
helper_iwmmxt_addul \
helper_iwmmxt_subsb \
helper_iwmmxt_subsw \
helper_iwmmxt_subsl \
helper_iwmmxt_addsb \
helper_iwmmxt_addsw \
helper_iwmmxt_addsl \
helper_iwmmxt_avgb0 \
helper_iwmmxt_avgb1 \
helper_iwmmxt_avgw0 \
helper_iwmmxt_avgw1 \
helper_iwmmxt_align \
helper_iwmmxt_insr \
helper_iwmmxt_setpsr_nz \
helper_iwmmxt_bcstb \
helper_iwmmxt_bcstw \
helper_iwmmxt_bcstl \
helper_iwmmxt_addcb \
helper_iwmmxt_addcw \
helper_iwmmxt_addcl \
helper_iwmmxt_msbb \
helper_iwmmxt_msbw \
helper_iwmmxt_msbl \
helper_iwmmxt_srlw \
helper_iwmmxt_srll \
helper_iwmmxt_srlq \
helper_iwmmxt_sllw \
helper_iwmmxt_slll \
helper_iwmmxt_sllq \
helper_iwmmxt_sraw \
helper_iwmmxt_sral \
helper_iwmmxt_sraq \
helper_iwmmxt_rorw \
helper_iwmmxt_rorl \
helper_iwmmxt_rorq \
helper_iwmmxt_shufh \
helper_iwmmxt_packuw \
helper_iwmmxt_packul \
helper_iwmmxt_packuq \
helper_iwmmxt_packsw \
helper_iwmmxt_packsl \
helper_iwmmxt_packsq \
helper_iwmmxt_muladdsl \
helper_iwmmxt_muladdsw \
helper_iwmmxt_muladdswl \
armv7m_nvic_set_pending \
helper_v7m_preserve_fp_state \
write_v7m_exception \
helper_v7m_bxns \
helper_v7m_blxns \
armv7m_nvic_neg_prio_requested \
helper_v7m_vlstm \
helper_v7m_vlldm \
arm_v7m_cpu_do_interrupt \
helper_v7m_mrs \
helper_v7m_msr \
helper_v7m_tt \
arm_v7m_mmu_idx_all \
arm_v7m_mmu_idx_for_secstate_and_priv \
arm_v7m_mmu_idx_for_secstate \
helper_neon_qadd_u8 \
helper_neon_qadd_u16 \
helper_neon_qadd_u32 \
helper_neon_qadd_u64 \
helper_neon_qadd_s8 \
helper_neon_qadd_s16 \
helper_neon_qadd_s32 \
helper_neon_qadd_s64 \
helper_neon_uqadd_s8 \
helper_neon_uqadd_s16 \
helper_neon_uqadd_s32 \
helper_neon_uqadd_s64 \
helper_neon_sqadd_u8 \
helper_neon_sqadd_u16 \
helper_neon_sqadd_u32 \
helper_neon_sqadd_u64 \
helper_neon_qsub_u8 \
helper_neon_qsub_u16 \
helper_neon_qsub_u32 \
helper_neon_qsub_u64 \
helper_neon_qsub_s8 \
helper_neon_qsub_s16 \
helper_neon_qsub_s32 \
helper_neon_qsub_s64 \
helper_neon_hadd_s8 \
helper_neon_hadd_u8 \
helper_neon_hadd_s16 \
helper_neon_hadd_u16 \
helper_neon_hadd_s32 \
helper_neon_hadd_u32 \
helper_neon_rhadd_s8 \
helper_neon_rhadd_u8 \
helper_neon_rhadd_s16 \
helper_neon_rhadd_u16 \
helper_neon_rhadd_s32 \
helper_neon_rhadd_u32 \
helper_neon_hsub_s8 \
helper_neon_hsub_u8 \
helper_neon_hsub_s16 \
helper_neon_hsub_u16 \
helper_neon_hsub_s32 \
helper_neon_hsub_u32 \
helper_neon_cgt_s8 \
helper_neon_cgt_u8 \
helper_neon_cgt_s16 \
helper_neon_cgt_u16 \
helper_neon_cgt_s32 \
helper_neon_cgt_u32 \
helper_neon_cge_s8 \
helper_neon_cge_u8 \
helper_neon_cge_s16 \
helper_neon_cge_u16 \
helper_neon_cge_s32 \
helper_neon_cge_u32 \
helper_neon_pmin_s8 \
helper_neon_pmin_u8 \
helper_neon_pmin_s16 \
helper_neon_pmin_u16 \
helper_neon_pmax_s8 \
helper_neon_pmax_u8 \
helper_neon_pmax_s16 \
helper_neon_pmax_u16 \
helper_neon_abd_s8 \
helper_neon_abd_u8 \
helper_neon_abd_s16 \
helper_neon_abd_u16 \
helper_neon_abd_s32 \
helper_neon_abd_u32 \
helper_neon_shl_u16 \
helper_neon_shl_s16 \
helper_neon_rshl_s8 \
helper_neon_rshl_s16 \
helper_neon_rshl_s32 \
helper_neon_rshl_s64 \
helper_neon_rshl_u8 \
helper_neon_rshl_u16 \
helper_neon_rshl_u32 \
helper_neon_rshl_u64 \
helper_neon_qshl_u8 \
helper_neon_qshl_u16 \
helper_neon_qshl_u32 \
helper_neon_qshl_u64 \
helper_neon_qshl_s8 \
helper_neon_qshl_s16 \
helper_neon_qshl_s32 \
helper_neon_qshl_s64 \
helper_neon_qshlu_s8 \
helper_neon_qshlu_s16 \
helper_neon_qshlu_s32 \
helper_neon_qshlu_s64 \
helper_neon_qrshl_u8 \
helper_neon_qrshl_u16 \
helper_neon_qrshl_u32 \
helper_neon_qrshl_u64 \
helper_neon_qrshl_s8 \
helper_neon_qrshl_s16 \
helper_neon_qrshl_s32 \
helper_neon_qrshl_s64 \
helper_neon_add_u8 \
helper_neon_add_u16 \
helper_neon_padd_u8 \
helper_neon_padd_u16 \
helper_neon_sub_u8 \
helper_neon_sub_u16 \
helper_neon_mul_u8 \
helper_neon_mul_u16 \
helper_neon_tst_u8 \
helper_neon_tst_u16 \
helper_neon_tst_u32 \
helper_neon_ceq_u8 \
helper_neon_ceq_u16 \
helper_neon_ceq_u32 \
helper_neon_clz_u8 \
helper_neon_clz_u16 \
helper_neon_cls_s8 \
helper_neon_cls_s16 \
helper_neon_cls_s32 \
helper_neon_cnt_u8 \
helper_neon_rbit_u8 \
helper_neon_qdmulh_s16 \
helper_neon_qrdmulh_s16 \
helper_neon_qdmulh_s32 \
helper_neon_qrdmulh_s32 \
helper_neon_narrow_u8 \
helper_neon_narrow_u16 \
helper_neon_narrow_high_u8 \
helper_neon_narrow_high_u16 \
helper_neon_narrow_round_high_u8 \
helper_neon_narrow_round_high_u16 \
helper_neon_unarrow_sat8 \
helper_neon_narrow_sat_u8 \
helper_neon_narrow_sat_s8 \
helper_neon_unarrow_sat16 \
helper_neon_narrow_sat_u16 \
helper_neon_narrow_sat_s16 \
helper_neon_unarrow_sat32 \
helper_neon_narrow_sat_u32 \
helper_neon_narrow_sat_s32 \
helper_neon_widen_u8 \
helper_neon_widen_s8 \
helper_neon_widen_u16 \
helper_neon_widen_s16 \
helper_neon_addl_u16 \
helper_neon_addl_u32 \
helper_neon_paddl_u16 \
helper_neon_paddl_u32 \
helper_neon_subl_u16 \
helper_neon_subl_u32 \
helper_neon_addl_saturate_s32 \
helper_neon_addl_saturate_s64 \
helper_neon_abdl_u16 \
helper_neon_abdl_s16 \
helper_neon_abdl_u32 \
helper_neon_abdl_s32 \
helper_neon_abdl_u64 \
helper_neon_abdl_s64 \
helper_neon_mull_u8 \
helper_neon_mull_s8 \
helper_neon_mull_u16 \
helper_neon_mull_s16 \
helper_neon_negl_u16 \
helper_neon_negl_u32 \
helper_neon_qabs_s8 \
helper_neon_qneg_s8 \
helper_neon_qabs_s16 \
helper_neon_qneg_s16 \
helper_neon_qabs_s32 \
helper_neon_qneg_s32 \
helper_neon_qabs_s64 \
helper_neon_qneg_s64 \
helper_neon_abd_f32 \
helper_neon_ceq_f32 \
helper_neon_cge_f32 \
helper_neon_cgt_f32 \
helper_neon_acge_f32 \
helper_neon_acgt_f32 \
helper_neon_acge_f64 \
helper_neon_acgt_f64 \
helper_neon_qunzip8 \
helper_neon_qunzip16 \
helper_neon_qunzip32 \
helper_neon_unzip8 \
helper_neon_unzip16 \
helper_neon_qzip8 \
helper_neon_qzip16 \
helper_neon_qzip32 \
helper_neon_zip8 \
helper_neon_zip16 \
raise_exception \
raise_exception_ra \
helper_neon_tbl \
helper_v8m_stackcheck \
helper_add_setq \
helper_add_saturate \
helper_sub_saturate \
helper_add_usaturate \
helper_sub_usaturate \
helper_ssat \
helper_ssat16 \
helper_usat \
helper_usat16 \
helper_setend \
helper_wfi \
helper_wfe \
helper_yield \
helper_exception_internal \
helper_exception_with_syndrome \
helper_exception_bkpt_insn \
helper_cpsr_read \
helper_cpsr_write \
helper_cpsr_write_eret \
helper_get_user_reg \
helper_set_user_reg \
helper_set_r13_banked \
helper_get_r13_banked \
helper_msr_banked \
helper_mrs_banked \
helper_access_check_cp_reg \
helper_set_cp_reg \
helper_get_cp_reg \
helper_set_cp_reg64 \
helper_get_cp_reg64 \
helper_pre_hvc \
helper_pre_smc \
helper_shl_cc \
helper_shr_cc \
helper_sar_cc \
helper_ror_cc \
helper_pacia \
helper_pacib \
helper_pacda \
helper_pacdb \
helper_pacga \
helper_autia \
helper_autib \
helper_autda \
helper_autdb \
helper_xpaci \
helper_xpacd \
arm_is_psci_call \
arm_handle_psci_call \
helper_sve_predtest1 \
helper_sve_predtest \
helper_sve_and_pppp \
helper_sve_bic_pppp \
helper_sve_eor_pppp \
helper_sve_sel_pppp \
helper_sve_orr_pppp \
helper_sve_orn_pppp \
helper_sve_nor_pppp \
helper_sve_nand_pppp \
helper_sve_and_zpzz_b \
helper_sve_and_zpzz_h \
helper_sve_and_zpzz_s \
helper_sve_and_zpzz_d \
helper_sve_orr_zpzz_b \
helper_sve_orr_zpzz_h \
helper_sve_orr_zpzz_s \
helper_sve_orr_zpzz_d \
helper_sve_eor_zpzz_b \
helper_sve_eor_zpzz_h \
helper_sve_eor_zpzz_s \
helper_sve_eor_zpzz_d \
helper_sve_bic_zpzz_b \
helper_sve_bic_zpzz_h \
helper_sve_bic_zpzz_s \
helper_sve_bic_zpzz_d \
helper_sve_add_zpzz_b \
helper_sve_add_zpzz_h \
helper_sve_add_zpzz_s \
helper_sve_add_zpzz_d \
helper_sve_sub_zpzz_b \
helper_sve_sub_zpzz_h \
helper_sve_sub_zpzz_s \
helper_sve_sub_zpzz_d \
helper_sve_smax_zpzz_b \
helper_sve_smax_zpzz_h \
helper_sve_smax_zpzz_s \
helper_sve_smax_zpzz_d \
helper_sve_umax_zpzz_b \
helper_sve_umax_zpzz_h \
helper_sve_umax_zpzz_s \
helper_sve_umax_zpzz_d \
helper_sve_smin_zpzz_b \
helper_sve_smin_zpzz_h \
helper_sve_smin_zpzz_s \
helper_sve_smin_zpzz_d \
helper_sve_umin_zpzz_b \
helper_sve_umin_zpzz_h \
helper_sve_umin_zpzz_s \
helper_sve_umin_zpzz_d \
helper_sve_sabd_zpzz_b \
helper_sve_sabd_zpzz_h \
helper_sve_sabd_zpzz_s \
helper_sve_sabd_zpzz_d \
helper_sve_uabd_zpzz_b \
helper_sve_uabd_zpzz_h \
helper_sve_uabd_zpzz_s \
helper_sve_uabd_zpzz_d \
helper_sve_mul_zpzz_b \
helper_sve_mul_zpzz_h \
helper_sve_mul_zpzz_s \
helper_sve_mul_zpzz_d \
helper_sve_smulh_zpzz_b \
helper_sve_smulh_zpzz_h \
helper_sve_smulh_zpzz_s \
helper_sve_smulh_zpzz_d \
helper_sve_umulh_zpzz_b \
helper_sve_umulh_zpzz_h \
helper_sve_umulh_zpzz_s \
helper_sve_umulh_zpzz_d \
helper_sve_sdiv_zpzz_s \
helper_sve_sdiv_zpzz_d \
helper_sve_udiv_zpzz_s \
helper_sve_udiv_zpzz_d \
helper_sve_asr_zpzz_b \
helper_sve_lsr_zpzz_b \
helper_sve_lsl_zpzz_b \
helper_sve_asr_zpzz_h \
helper_sve_lsr_zpzz_h \
helper_sve_lsl_zpzz_h \
helper_sve_asr_zpzz_s \
helper_sve_lsr_zpzz_s \
helper_sve_lsl_zpzz_s \
helper_sve_asr_zpzz_d \
helper_sve_lsr_zpzz_d \
helper_sve_lsl_zpzz_d \
helper_sve_asr_zpzw_b \
helper_sve_lsr_zpzw_b \
helper_sve_lsl_zpzw_b \
helper_sve_asr_zpzw_h \
helper_sve_lsr_zpzw_h \
helper_sve_lsl_zpzw_h \
helper_sve_asr_zpzw_s \
helper_sve_lsr_zpzw_s \
helper_sve_lsl_zpzw_s \
helper_sve_cls_b \
helper_sve_cls_h \
helper_sve_cls_s \
helper_sve_cls_d \
helper_sve_clz_b \
helper_sve_clz_h \
helper_sve_clz_s \
helper_sve_clz_d \
helper_sve_cnt_zpz_b \
helper_sve_cnt_zpz_h \
helper_sve_cnt_zpz_s \
helper_sve_cnt_zpz_d \
helper_sve_cnot_b \
helper_sve_cnot_h \
helper_sve_cnot_s \
helper_sve_cnot_d \
helper_sve_fabs_h \
helper_sve_fabs_s \
helper_sve_fabs_d \
helper_sve_fneg_h \
helper_sve_fneg_s \
helper_sve_fneg_d \
helper_sve_not_zpz_b \
helper_sve_not_zpz_h \
helper_sve_not_zpz_s \
helper_sve_not_zpz_d \
helper_sve_sxtb_h \
helper_sve_sxtb_s \
helper_sve_sxth_s \
helper_sve_sxtb_d \
helper_sve_sxth_d \
helper_sve_sxtw_d \
helper_sve_uxtb_h \
helper_sve_uxtb_s \
helper_sve_uxth_s \
helper_sve_uxtb_d \
helper_sve_uxth_d \
helper_sve_uxtw_d \
helper_sve_abs_b \
helper_sve_abs_h \
helper_sve_abs_s \
helper_sve_abs_d \
helper_sve_neg_b \
helper_sve_neg_h \
helper_sve_neg_s \
helper_sve_neg_d \
helper_sve_revb_h \
helper_sve_revb_s \
helper_sve_revb_d \
helper_sve_revh_s \
helper_sve_revh_d \
helper_sve_revw_d \
helper_sve_rbit_b \
helper_sve_rbit_h \
helper_sve_rbit_s \
helper_sve_rbit_d \
helper_sve_asr_zzw_b \
helper_sve_lsr_zzw_b \
helper_sve_lsl_zzw_b \
helper_sve_asr_zzw_h \
helper_sve_lsr_zzw_h \
helper_sve_lsl_zzw_h \
helper_sve_asr_zzw_s \
helper_sve_lsr_zzw_s \
helper_sve_lsl_zzw_s \
helper_sve_orv_b \
helper_sve_orv_h \
helper_sve_orv_s \
helper_sve_orv_d \
helper_sve_eorv_b \
helper_sve_eorv_h \
helper_sve_eorv_s \
helper_sve_eorv_d \
helper_sve_andv_b \
helper_sve_andv_h \
helper_sve_andv_s \
helper_sve_andv_d \
helper_sve_saddv_b \
helper_sve_saddv_h \
helper_sve_saddv_s \
helper_sve_uaddv_b \
helper_sve_uaddv_h \
helper_sve_uaddv_s \
helper_sve_uaddv_d \
helper_sve_smaxv_b \
helper_sve_smaxv_h \
helper_sve_smaxv_s \
helper_sve_smaxv_d \
helper_sve_umaxv_b \
helper_sve_umaxv_h \
helper_sve_umaxv_s \
helper_sve_umaxv_d \
helper_sve_sminv_b \
helper_sve_sminv_h \
helper_sve_sminv_s \
helper_sve_sminv_d \
helper_sve_uminv_b \
helper_sve_uminv_h \
helper_sve_uminv_s \
helper_sve_uminv_d \
helper_sve_subri_b \
helper_sve_subri_h \
helper_sve_subri_s \
helper_sve_subri_d \
helper_sve_smaxi_b \
helper_sve_smaxi_h \
helper_sve_smaxi_s \
helper_sve_smaxi_d \
helper_sve_smini_b \
helper_sve_smini_h \
helper_sve_smini_s \
helper_sve_smini_d \
helper_sve_umaxi_b \
helper_sve_umaxi_h \
helper_sve_umaxi_s \
helper_sve_umaxi_d \
helper_sve_umini_b \
helper_sve_umini_h \
helper_sve_umini_s \
helper_sve_umini_d \
helper_sve_pfirst \
helper_sve_pnext \
helper_sve_clr_b \
helper_sve_clr_h \
helper_sve_clr_s \
helper_sve_clr_d \
helper_sve_movz_b \
helper_sve_movz_h \
helper_sve_movz_s \
helper_sve_movz_d \
helper_sve_asr_zpzi_b \
helper_sve_asr_zpzi_h \
helper_sve_asr_zpzi_s \
helper_sve_asr_zpzi_d \
helper_sve_lsr_zpzi_b \
helper_sve_lsr_zpzi_h \
helper_sve_lsr_zpzi_s \
helper_sve_lsr_zpzi_d \
helper_sve_lsl_zpzi_b \
helper_sve_lsl_zpzi_h \
helper_sve_lsl_zpzi_s \
helper_sve_lsl_zpzi_d \
helper_sve_asrd_b \
helper_sve_asrd_h \
helper_sve_asrd_s \
helper_sve_asrd_d \
helper_sve_mla_b \
helper_sve_mls_b \
helper_sve_mla_h \
helper_sve_mls_h \
helper_sve_mla_s \
helper_sve_mls_s \
helper_sve_mla_d \
helper_sve_mls_d \
helper_sve_index_b \
helper_sve_index_h \
helper_sve_index_s \
helper_sve_index_d \
helper_sve_adr_p32 \
helper_sve_adr_p64 \
helper_sve_adr_s32 \
helper_sve_adr_u32 \
helper_sve_fexpa_h \
helper_sve_fexpa_s \
helper_sve_fexpa_d \
helper_sve_ftssel_h \
helper_sve_ftssel_s \
helper_sve_ftssel_d \
helper_sve_sqaddi_b \
helper_sve_sqaddi_h \
helper_sve_sqaddi_s \
helper_sve_sqaddi_d \
helper_sve_uqaddi_b \
helper_sve_uqaddi_h \
helper_sve_uqaddi_s \
helper_sve_uqaddi_d \
helper_sve_uqsubi_d \
helper_sve_cpy_m_b \
helper_sve_cpy_m_h \
helper_sve_cpy_m_s \
helper_sve_cpy_m_d \
helper_sve_cpy_z_b \
helper_sve_cpy_z_h \
helper_sve_cpy_z_s \
helper_sve_cpy_z_d \
helper_sve_ext \
helper_sve_insr_b \
helper_sve_insr_h \
helper_sve_insr_s \
helper_sve_insr_d \
helper_sve_rev_b \
helper_sve_rev_h \
helper_sve_rev_s \
helper_sve_rev_d \
helper_sve_tbl_b \
helper_sve_tbl_h \
helper_sve_tbl_s \
helper_sve_tbl_d \
helper_sve_sunpk_h \
helper_sve_sunpk_s \
helper_sve_sunpk_d \
helper_sve_uunpk_h \
helper_sve_uunpk_s \
helper_sve_uunpk_d \
helper_sve_zip_p \
helper_sve_uzp_p \
helper_sve_trn_p \
helper_sve_rev_p \
helper_sve_punpk_p \
helper_sve_zip_b \
helper_sve_zip_h \
helper_sve_zip_s \
helper_sve_zip_d \
helper_sve_uzp_b \
helper_sve_uzp_h \
helper_sve_uzp_s \
helper_sve_uzp_d \
helper_sve_trn_b \
helper_sve_trn_h \
helper_sve_trn_s \
helper_sve_trn_d \
helper_sve_compact_s \
helper_sve_compact_d \
helper_sve_last_active_element \
helper_sve_splice \
helper_sve_sel_zpzz_b \
helper_sve_sel_zpzz_h \
helper_sve_sel_zpzz_s \
helper_sve_sel_zpzz_d \
helper_sve_cmpeq_ppzz_b \
helper_sve_cmpeq_ppzz_h \
helper_sve_cmpeq_ppzz_s \
helper_sve_cmpeq_ppzz_d \
helper_sve_cmpne_ppzz_b \
helper_sve_cmpne_ppzz_h \
helper_sve_cmpne_ppzz_s \
helper_sve_cmpne_ppzz_d \
helper_sve_cmpgt_ppzz_b \
helper_sve_cmpgt_ppzz_h \
helper_sve_cmpgt_ppzz_s \
helper_sve_cmpgt_ppzz_d \
helper_sve_cmpge_ppzz_b \
helper_sve_cmpge_ppzz_h \
helper_sve_cmpge_ppzz_s \
helper_sve_cmpge_ppzz_d \
helper_sve_cmphi_ppzz_b \
helper_sve_cmphi_ppzz_h \
helper_sve_cmphi_ppzz_s \
helper_sve_cmphi_ppzz_d \
helper_sve_cmphs_ppzz_b \
helper_sve_cmphs_ppzz_h \
helper_sve_cmphs_ppzz_s \
helper_sve_cmphs_ppzz_d \
helper_sve_cmpeq_ppzw_b \
helper_sve_cmpeq_ppzw_h \
helper_sve_cmpeq_ppzw_s \
helper_sve_cmpne_ppzw_b \
helper_sve_cmpne_ppzw_h \
helper_sve_cmpne_ppzw_s \
helper_sve_cmpgt_ppzw_b \
helper_sve_cmpgt_ppzw_h \
helper_sve_cmpgt_ppzw_s \
helper_sve_cmpge_ppzw_b \
helper_sve_cmpge_ppzw_h \
helper_sve_cmpge_ppzw_s \
helper_sve_cmphi_ppzw_b \
helper_sve_cmphi_ppzw_h \
helper_sve_cmphi_ppzw_s \
helper_sve_cmphs_ppzw_b \
helper_sve_cmphs_ppzw_h \
helper_sve_cmphs_ppzw_s \
helper_sve_cmplt_ppzw_b \
helper_sve_cmplt_ppzw_h \
helper_sve_cmplt_ppzw_s \
helper_sve_cmple_ppzw_b \
helper_sve_cmple_ppzw_h \
helper_sve_cmple_ppzw_s \
helper_sve_cmplo_ppzw_b \
helper_sve_cmplo_ppzw_h \
helper_sve_cmplo_ppzw_s \
helper_sve_cmpls_ppzw_b \
helper_sve_cmpls_ppzw_h \
helper_sve_cmpls_ppzw_s \
helper_sve_cmpeq_ppzi_b \
helper_sve_cmpeq_ppzi_h \
helper_sve_cmpeq_ppzi_s \
helper_sve_cmpeq_ppzi_d \
helper_sve_cmpne_ppzi_b \
helper_sve_cmpne_ppzi_h \
helper_sve_cmpne_ppzi_s \
helper_sve_cmpne_ppzi_d \
helper_sve_cmpgt_ppzi_b \
helper_sve_cmpgt_ppzi_h \
helper_sve_cmpgt_ppzi_s \
helper_sve_cmpgt_ppzi_d \
helper_sve_cmpge_ppzi_b \
helper_sve_cmpge_ppzi_h \
helper_sve_cmpge_ppzi_s \
helper_sve_cmpge_ppzi_d \
helper_sve_cmphi_ppzi_b \
helper_sve_cmphi_ppzi_h \
helper_sve_cmphi_ppzi_s \
helper_sve_cmphi_ppzi_d \
helper_sve_cmphs_ppzi_b \
helper_sve_cmphs_ppzi_h \
helper_sve_cmphs_ppzi_s \
helper_sve_cmphs_ppzi_d \
helper_sve_cmplt_ppzi_b \
helper_sve_cmplt_ppzi_h \
helper_sve_cmplt_ppzi_s \
helper_sve_cmplt_ppzi_d \
helper_sve_cmple_ppzi_b \
helper_sve_cmple_ppzi_h \
helper_sve_cmple_ppzi_s \
helper_sve_cmple_ppzi_d \
helper_sve_cmplo_ppzi_b \
helper_sve_cmplo_ppzi_h \
helper_sve_cmplo_ppzi_s \
helper_sve_cmplo_ppzi_d \
helper_sve_cmpls_ppzi_b \
helper_sve_cmpls_ppzi_h \
helper_sve_cmpls_ppzi_s \
helper_sve_cmpls_ppzi_d \
helper_sve_brkpa \
helper_sve_brkpas \
helper_sve_brkpb \
helper_sve_brkpbs \
helper_sve_brka_z \
helper_sve_brkas_z \
helper_sve_brkb_z \
helper_sve_brkbs_z \
helper_sve_brka_m \
helper_sve_brkas_m \
helper_sve_brkb_m \
helper_sve_brkbs_m \
helper_sve_brkn \
helper_sve_brkns \
helper_sve_cntp \
helper_sve_while \
helper_sve_faddv_h \
helper_sve_faddv_s \
helper_sve_faddv_d \
helper_sve_fminnmv_h \
helper_sve_fminnmv_s \
helper_sve_fminnmv_d \
helper_sve_fmaxnmv_h \
helper_sve_fmaxnmv_s \
helper_sve_fmaxnmv_d \
helper_sve_fminv_h \
helper_sve_fminv_s \
helper_sve_fminv_d \
helper_sve_fmaxv_h \
helper_sve_fmaxv_s \
helper_sve_fmaxv_d \
helper_sve_fadda_h \
helper_sve_fadda_s \
helper_sve_fadda_d \
helper_sve_fadd_h \
helper_sve_fadd_s \
helper_sve_fadd_d \
helper_sve_fsub_h \
helper_sve_fsub_s \
helper_sve_fsub_d \
helper_sve_fmul_h \
helper_sve_fmul_s \
helper_sve_fmul_d \
helper_sve_fdiv_h \
helper_sve_fdiv_s \
helper_sve_fdiv_d \
helper_sve_fmin_h \
helper_sve_fmin_s \
helper_sve_fmin_d \
helper_sve_fmax_h \
helper_sve_fmax_s \
helper_sve_fmax_d \
helper_sve_fminnum_h \
helper_sve_fminnum_s \
helper_sve_fminnum_d \
helper_sve_fmaxnum_h \
helper_sve_fmaxnum_s \
helper_sve_fmaxnum_d \
helper_sve_fabd_h \
helper_sve_fabd_s \
helper_sve_fabd_d \
helper_sve_fscalbn_h \
helper_sve_fscalbn_s \
helper_sve_fscalbn_d \
helper_sve_fmulx_h \
helper_sve_fmulx_s \
helper_sve_fmulx_d \
helper_sve_fadds_h \
helper_sve_fadds_s \
helper_sve_fadds_d \
helper_sve_fsubs_h \
helper_sve_fsubs_s \
helper_sve_fsubs_d \
helper_sve_fmuls_h \
helper_sve_fmuls_s \
helper_sve_fmuls_d \
helper_sve_fsubrs_h \
helper_sve_fsubrs_s \
helper_sve_fsubrs_d \
helper_sve_fmaxnms_h \
helper_sve_fmaxnms_s \
helper_sve_fmaxnms_d \
helper_sve_fminnms_h \
helper_sve_fminnms_s \
helper_sve_fminnms_d \
helper_sve_fmaxs_h \
helper_sve_fmaxs_s \
helper_sve_fmaxs_d \
helper_sve_fmins_h \
helper_sve_fmins_s \
helper_sve_fmins_d \
helper_sve_fcvt_sh \
helper_sve_fcvt_hs \
helper_sve_fcvt_dh \
helper_sve_fcvt_hd \
helper_sve_fcvt_ds \
helper_sve_fcvt_sd \
helper_sve_fcvtzs_hh \
helper_sve_fcvtzs_hs \
helper_sve_fcvtzs_ss \
helper_sve_fcvtzs_hd \
helper_sve_fcvtzs_sd \
helper_sve_fcvtzs_ds \
helper_sve_fcvtzs_dd \
helper_sve_fcvtzu_hh \
helper_sve_fcvtzu_hs \
helper_sve_fcvtzu_ss \
helper_sve_fcvtzu_hd \
helper_sve_fcvtzu_sd \
helper_sve_fcvtzu_ds \
helper_sve_fcvtzu_dd \
helper_sve_frint_h \
helper_sve_frint_s \
helper_sve_frint_d \
helper_sve_frintx_h \
helper_sve_frintx_s \
helper_sve_frintx_d \
helper_sve_frecpx_h \
helper_sve_frecpx_s \
helper_sve_frecpx_d \
helper_sve_fsqrt_h \
helper_sve_fsqrt_s \
helper_sve_fsqrt_d \
helper_sve_scvt_hh \
helper_sve_scvt_sh \
helper_sve_scvt_ss \
helper_sve_scvt_sd \
helper_sve_scvt_dh \
helper_sve_scvt_ds \
helper_sve_scvt_dd \
helper_sve_ucvt_hh \
helper_sve_ucvt_sh \
helper_sve_ucvt_ss \
helper_sve_ucvt_sd \
helper_sve_ucvt_dh \
helper_sve_ucvt_ds \
helper_sve_ucvt_dd \
helper_sve_fmla_zpzzz_h \
helper_sve_fmls_zpzzz_h \
helper_sve_fnmla_zpzzz_h \
helper_sve_fnmls_zpzzz_h \
helper_sve_fmla_zpzzz_s \
helper_sve_fmls_zpzzz_s \
helper_sve_fnmla_zpzzz_s \
helper_sve_fnmls_zpzzz_s \
helper_sve_fmla_zpzzz_d \
helper_sve_fmls_zpzzz_d \
helper_sve_fnmla_zpzzz_d \
helper_sve_fnmls_zpzzz_d \
helper_sve_fcmge_h \
helper_sve_fcmge_s \
helper_sve_fcmge_d \
helper_sve_fcmgt_h \
helper_sve_fcmgt_s \
helper_sve_fcmgt_d \
helper_sve_fcmeq_h \
helper_sve_fcmeq_s \
helper_sve_fcmeq_d \
helper_sve_fcmne_h \
helper_sve_fcmne_s \
helper_sve_fcmne_d \
helper_sve_fcmuo_h \
helper_sve_fcmuo_s \
helper_sve_fcmuo_d \
helper_sve_facge_h \
helper_sve_facge_s \
helper_sve_facge_d \
helper_sve_facgt_h \
helper_sve_facgt_s \
helper_sve_facgt_d \
helper_sve_fcmge0_h \
helper_sve_fcmge0_s \
helper_sve_fcmge0_d \
helper_sve_fcmgt0_h \
helper_sve_fcmgt0_s \
helper_sve_fcmgt0_d \
helper_sve_fcmle0_h \
helper_sve_fcmle0_s \
helper_sve_fcmle0_d \
helper_sve_fcmlt0_h \
helper_sve_fcmlt0_s \
helper_sve_fcmlt0_d \
helper_sve_fcmeq0_h \
helper_sve_fcmeq0_s \
helper_sve_fcmeq0_d \
helper_sve_fcmne0_h \
helper_sve_fcmne0_s \
helper_sve_fcmne0_d \
helper_sve_ftmad_h \
helper_sve_ftmad_s \
helper_sve_ftmad_d \
helper_sve_fcadd_h \
helper_sve_fcadd_s \
helper_sve_fcadd_d \
helper_sve_fcmla_zpzzz_h \
helper_sve_fcmla_zpzzz_s \
helper_sve_fcmla_zpzzz_d \
helper_sve_ld1bb_r \
helper_sve_ld1bhu_r \
helper_sve_ld1bhs_r \
helper_sve_ld1bsu_r \
helper_sve_ld1bss_r \
helper_sve_ld1bdu_r \
helper_sve_ld1bds_r \
helper_sve_ld1hh_le_r \
helper_sve_ld1hh_be_r \
helper_sve_ld1hsu_le_r \
helper_sve_ld1hsu_be_r \
helper_sve_ld1hss_le_r \
helper_sve_ld1hss_be_r \
helper_sve_ld1hdu_le_r \
helper_sve_ld1hdu_be_r \
helper_sve_ld1hds_le_r \
helper_sve_ld1hds_be_r \
helper_sve_ld1ss_le_r \
helper_sve_ld1ss_be_r \
helper_sve_ld1sdu_le_r \
helper_sve_ld1sdu_be_r \
helper_sve_ld1sds_le_r \
helper_sve_ld1sds_be_r \
helper_sve_ld1dd_le_r \
helper_sve_ld1dd_be_r \
helper_sve_ld2bb_r \
helper_sve_ld3bb_r \
helper_sve_ld4bb_r \
helper_sve_ld2hh_le_r \
helper_sve_ld2hh_be_r \
helper_sve_ld3hh_le_r \
helper_sve_ld3hh_be_r \
helper_sve_ld4hh_le_r \
helper_sve_ld4hh_be_r \
helper_sve_ld2ss_le_r \
helper_sve_ld2ss_be_r \
helper_sve_ld3ss_le_r \
helper_sve_ld3ss_be_r \
helper_sve_ld4ss_le_r \
helper_sve_ld4ss_be_r \
helper_sve_ld2dd_le_r \
helper_sve_ld2dd_be_r \
helper_sve_ld3dd_le_r \
helper_sve_ld3dd_be_r \
helper_sve_ld4dd_le_r \
helper_sve_ld4dd_be_r \
helper_sve_ldff1bb_r \
helper_sve_ldnf1bb_r \
helper_sve_ldff1bhu_r \
helper_sve_ldnf1bhu_r \
helper_sve_ldff1bhs_r \
helper_sve_ldnf1bhs_r \
helper_sve_ldff1bsu_r \
helper_sve_ldnf1bsu_r \
helper_sve_ldff1bss_r \
helper_sve_ldnf1bss_r \
helper_sve_ldff1bdu_r \
helper_sve_ldnf1bdu_r \
helper_sve_ldff1bds_r \
helper_sve_ldnf1bds_r \
helper_sve_ldff1hh_le_r \
helper_sve_ldnf1hh_le_r \
helper_sve_ldff1hh_be_r \
helper_sve_ldnf1hh_be_r \
helper_sve_ldff1hsu_le_r \
helper_sve_ldnf1hsu_le_r \
helper_sve_ldff1hsu_be_r \
helper_sve_ldnf1hsu_be_r \
helper_sve_ldff1hss_le_r \
helper_sve_ldnf1hss_le_r \
helper_sve_ldff1hss_be_r \
helper_sve_ldnf1hss_be_r \
helper_sve_ldff1hdu_le_r \
helper_sve_ldnf1hdu_le_r \
helper_sve_ldff1hdu_be_r \
helper_sve_ldnf1hdu_be_r \
helper_sve_ldff1hds_le_r \
helper_sve_ldnf1hds_le_r \
helper_sve_ldff1hds_be_r \
helper_sve_ldnf1hds_be_r \
helper_sve_ldff1ss_le_r \
helper_sve_ldnf1ss_le_r \
helper_sve_ldff1ss_be_r \
helper_sve_ldnf1ss_be_r \
helper_sve_ldff1sdu_le_r \
helper_sve_ldnf1sdu_le_r \
helper_sve_ldff1sdu_be_r \
helper_sve_ldnf1sdu_be_r \
helper_sve_ldff1sds_le_r \
helper_sve_ldnf1sds_le_r \
helper_sve_ldff1sds_be_r \
helper_sve_ldnf1sds_be_r \
helper_sve_ldff1dd_le_r \
helper_sve_ldnf1dd_le_r \
helper_sve_ldff1dd_be_r \
helper_sve_ldnf1dd_be_r \
helper_sve_st1bb_r \
helper_sve_st1bh_r \
helper_sve_st1bs_r \
helper_sve_st1bd_r \
helper_sve_st2bb_r \
helper_sve_st3bb_r \
helper_sve_st4bb_r \
helper_sve_st1hh_le_r \
helper_sve_st1hh_be_r \
helper_sve_st1hs_le_r \
helper_sve_st1hs_be_r \
helper_sve_st1hd_le_r \
helper_sve_st1hd_be_r \
helper_sve_st2hh_le_r \
helper_sve_st2hh_be_r \
helper_sve_st3hh_le_r \
helper_sve_st3hh_be_r \
helper_sve_st4hh_le_r \
helper_sve_st4hh_be_r \
helper_sve_st1ss_le_r \
helper_sve_st1ss_be_r \
helper_sve_st1sd_le_r \
helper_sve_st1sd_be_r \
helper_sve_st2ss_le_r \
helper_sve_st2ss_be_r \
helper_sve_st3ss_le_r \
helper_sve_st3ss_be_r \
helper_sve_st4ss_le_r \
helper_sve_st4ss_be_r \
helper_sve_st1dd_le_r \
helper_sve_st1dd_be_r \
helper_sve_st2dd_le_r \
helper_sve_st2dd_be_r \
helper_sve_st3dd_le_r \
helper_sve_st3dd_be_r \
helper_sve_st4dd_le_r \
helper_sve_st4dd_be_r \
helper_sve_ldbsu_zsu \
helper_sve_ldbsu_zss \
helper_sve_ldbdu_zsu \
helper_sve_ldbdu_zss \
helper_sve_ldbdu_zd \
helper_sve_ldbss_zsu \
helper_sve_ldbss_zss \
helper_sve_ldbds_zsu \
helper_sve_ldbds_zss \
helper_sve_ldbds_zd \
helper_sve_ldhsu_le_zsu \
helper_sve_ldhsu_le_zss \
helper_sve_ldhdu_le_zsu \
helper_sve_ldhdu_le_zss \
helper_sve_ldhdu_le_zd \
helper_sve_ldhsu_be_zsu \
helper_sve_ldhsu_be_zss \
helper_sve_ldhdu_be_zsu \
helper_sve_ldhdu_be_zss \
helper_sve_ldhdu_be_zd \
helper_sve_ldhss_le_zsu \
helper_sve_ldhss_le_zss \
helper_sve_ldhds_le_zsu \
helper_sve_ldhds_le_zss \
helper_sve_ldhds_le_zd \
helper_sve_ldhss_be_zsu \
helper_sve_ldhss_be_zss \
helper_sve_ldhds_be_zsu \
helper_sve_ldhds_be_zss \
helper_sve_ldhds_be_zd \
helper_sve_ldss_le_zsu \
helper_sve_ldss_le_zss \
helper_sve_ldsdu_le_zsu \
helper_sve_ldsdu_le_zss \
helper_sve_ldsdu_le_zd \
helper_sve_ldss_be_zsu \
helper_sve_ldss_be_zss \
helper_sve_ldsdu_be_zsu \
helper_sve_ldsdu_be_zss \
helper_sve_ldsdu_be_zd \
helper_sve_ldsds_le_zsu \
helper_sve_ldsds_le_zss \
helper_sve_ldsds_le_zd \
helper_sve_ldsds_be_zsu \
helper_sve_ldsds_be_zss \
helper_sve_ldsds_be_zd \
helper_sve_lddd_le_zsu \
helper_sve_lddd_le_zss \
helper_sve_lddd_le_zd \
helper_sve_lddd_be_zsu \
helper_sve_lddd_be_zss \
helper_sve_lddd_be_zd \
helper_sve_ldffbsu_zsu \
helper_sve_ldffbsu_zss \
helper_sve_ldffbdu_zsu \
helper_sve_ldffbdu_zss \
helper_sve_ldffbdu_zd \
helper_sve_ldffbss_zsu \
helper_sve_ldffbss_zss \
helper_sve_ldffbds_zsu \
helper_sve_ldffbds_zss \
helper_sve_ldffbds_zd \
helper_sve_ldffhsu_le_zsu \
helper_sve_ldffhsu_le_zss \
helper_sve_ldffhdu_le_zsu \
helper_sve_ldffhdu_le_zss \
helper_sve_ldffhdu_le_zd \
helper_sve_ldffhsu_be_zsu \
helper_sve_ldffhsu_be_zss \
helper_sve_ldffhdu_be_zsu \
helper_sve_ldffhdu_be_zss \
helper_sve_ldffhdu_be_zd \
helper_sve_ldffhss_le_zsu \
helper_sve_ldffhss_le_zss \
helper_sve_ldffhds_le_zsu \
helper_sve_ldffhds_le_zss \
helper_sve_ldffhds_le_zd \
helper_sve_ldffhss_be_zsu \
helper_sve_ldffhss_be_zss \
helper_sve_ldffhds_be_zsu \
helper_sve_ldffhds_be_zss \
helper_sve_ldffhds_be_zd \
helper_sve_ldffss_le_zsu \
helper_sve_ldffss_le_zss \
helper_sve_ldffsdu_le_zsu \
helper_sve_ldffsdu_le_zss \
helper_sve_ldffsdu_le_zd \
helper_sve_ldffss_be_zsu \
helper_sve_ldffss_be_zss \
helper_sve_ldffsdu_be_zsu \
helper_sve_ldffsdu_be_zss \
helper_sve_ldffsdu_be_zd \
helper_sve_ldffsds_le_zsu \
helper_sve_ldffsds_le_zss \
helper_sve_ldffsds_le_zd \
helper_sve_ldffsds_be_zsu \
helper_sve_ldffsds_be_zss \
helper_sve_ldffsds_be_zd \
helper_sve_ldffdd_le_zsu \
helper_sve_ldffdd_le_zss \
helper_sve_ldffdd_le_zd \
helper_sve_ldffdd_be_zsu \
helper_sve_ldffdd_be_zss \
helper_sve_ldffdd_be_zd \
helper_sve_stbs_zsu \
helper_sve_sths_le_zsu \
helper_sve_sths_be_zsu \
helper_sve_stss_le_zsu \
helper_sve_stss_be_zsu \
helper_sve_stbs_zss \
helper_sve_sths_le_zss \
helper_sve_sths_be_zss \
helper_sve_stss_le_zss \
helper_sve_stss_be_zss \
helper_sve_stbd_zsu \
helper_sve_sthd_le_zsu \
helper_sve_sthd_be_zsu \
helper_sve_stsd_le_zsu \
helper_sve_stsd_be_zsu \
helper_sve_stdd_le_zsu \
helper_sve_stdd_be_zsu \
helper_sve_stbd_zss \
helper_sve_sthd_le_zss \
helper_sve_sthd_be_zss \
helper_sve_stsd_le_zss \
helper_sve_stsd_be_zss \
helper_sve_stdd_le_zss \
helper_sve_stdd_be_zss \
helper_sve_stbd_zd \
helper_sve_sthd_le_zd \
helper_sve_sthd_be_zd \
helper_sve_stsd_le_zd \
helper_sve_stsd_be_zd \
helper_sve_stdd_le_zd \
helper_sve_stdd_be_zd \
arm_cpu_do_unaligned_access \
arm_cpu_do_transaction_failed \
arm_cpu_tlb_fill \
a64_translate_init \
gen_a64_set_pc_im \
unallocated_encoding \
new_tmp_a64 \
new_tmp_a64_zero \
cpu_reg \
cpu_reg_sp \
read_cpu_reg \
read_cpu_reg_sp \
write_fp_dreg \
get_fpstatus_ptr \
sve_access_check \
logic_imm_decode_wmask \
arm_translate_init \
arm_test_cc \
arm_free_cc \
arm_jump_cc \
arm_gen_test_cc \
vfp_expand_imm \
gen_cmtst_i64 \
gen_ushl_i32 \
gen_ushl_i64 \
gen_sshl_i32 \
gen_sshl_i64 \
gen_intermediate_code \
restore_state_to_opc \
disas_sve \
helper_neon_qrdmlah_s16 \
helper_gvec_qrdmlah_s16 \
helper_neon_qrdmlsh_s16 \
helper_gvec_qrdmlsh_s16 \
helper_neon_qrdmlah_s32 \
helper_gvec_qrdmlah_s32 \
helper_neon_qrdmlsh_s32 \
helper_gvec_qrdmlsh_s32 \
helper_gvec_sdot_b \
helper_gvec_udot_b \
helper_gvec_sdot_h \
helper_gvec_udot_h \
helper_gvec_sdot_idx_b \
helper_gvec_udot_idx_b \
helper_gvec_sdot_idx_h \
helper_gvec_udot_idx_h \
helper_gvec_fcaddh \
helper_gvec_fcadds \
helper_gvec_fcaddd \
helper_gvec_fcmlah \
helper_gvec_fcmlah_idx \
helper_gvec_fcmlas \
helper_gvec_fcmlas_idx \
helper_gvec_fcmlad \
helper_gvec_frecpe_h \
helper_gvec_frecpe_s \
helper_gvec_frecpe_d \
helper_gvec_frsqrte_h \
helper_gvec_frsqrte_s \
helper_gvec_frsqrte_d \
helper_gvec_fadd_h \
helper_gvec_fadd_s \
helper_gvec_fadd_d \
helper_gvec_fsub_h \
helper_gvec_fsub_s \
helper_gvec_fsub_d \
helper_gvec_fmul_h \
helper_gvec_fmul_s \
helper_gvec_fmul_d \
helper_gvec_ftsmul_h \
helper_gvec_ftsmul_s \
helper_gvec_ftsmul_d \
helper_gvec_recps_h \
helper_gvec_recps_s \
helper_gvec_recps_d \
helper_gvec_rsqrts_h \
helper_gvec_rsqrts_s \
helper_gvec_rsqrts_d \
helper_gvec_fmul_idx_h \
helper_gvec_fmul_idx_s \
helper_gvec_fmul_idx_d \
helper_gvec_fmla_idx_h \
helper_gvec_fmla_idx_s \
helper_gvec_fmla_idx_d \
helper_gvec_uqadd_b \
helper_gvec_uqadd_h \
helper_gvec_uqadd_s \
helper_gvec_sqadd_b \
helper_gvec_sqadd_h \
helper_gvec_sqadd_s \
helper_gvec_uqsub_b \
helper_gvec_uqsub_h \
helper_gvec_uqsub_s \
helper_gvec_sqsub_b \
helper_gvec_sqsub_h \
helper_gvec_sqsub_s \
helper_gvec_uqadd_d \
helper_gvec_uqsub_d \
helper_gvec_sqadd_d \
helper_gvec_sqsub_d \
helper_gvec_fmlal_a32 \
helper_gvec_fmlal_a64 \
helper_gvec_fmlal_idx_a32 \
helper_gvec_fmlal_idx_a64 \
helper_gvec_sshl_b \
helper_gvec_sshl_h \
helper_gvec_ushl_b \
helper_gvec_ushl_h \
helper_gvec_pmul_b \
helper_gvec_pmull_q \
helper_neon_pmull_h \
helper_sve2_pmull_h \
helper_vfp_get_fpscr \
vfp_get_fpscr \
helper_vfp_set_fpscr \
vfp_set_fpscr \
helper_vfp_adds \
helper_vfp_addd \
helper_vfp_subs \
helper_vfp_subd \
helper_vfp_muls \
helper_vfp_muld \
helper_vfp_divs \
helper_vfp_divd \
helper_vfp_mins \
helper_vfp_mind \
helper_vfp_maxs \
helper_vfp_maxd \
helper_vfp_minnums \
helper_vfp_minnumd \
helper_vfp_maxnums \
helper_vfp_maxnumd \
helper_vfp_negs \
helper_vfp_negd \
helper_vfp_abss \
helper_vfp_absd \
helper_vfp_sqrts \
helper_vfp_sqrtd \
helper_vfp_cmps \
helper_vfp_cmpes \
helper_vfp_cmpd \
helper_vfp_cmped \
helper_vfp_sitoh \
helper_vfp_tosih \
helper_vfp_tosizh \
helper_vfp_sitos \
helper_vfp_tosis \
helper_vfp_tosizs \
helper_vfp_sitod \
helper_vfp_tosid \
helper_vfp_tosizd \
helper_vfp_uitoh \
helper_vfp_touih \
helper_vfp_touizh \
helper_vfp_uitos \
helper_vfp_touis \
helper_vfp_touizs \
helper_vfp_uitod \
helper_vfp_touid \
helper_vfp_touizd \
helper_vfp_fcvtds \
helper_vfp_fcvtsd \
helper_vfp_shtod \
helper_vfp_toshd_round_to_zero \
helper_vfp_toshd \
helper_vfp_sltod \
helper_vfp_tosld_round_to_zero \
helper_vfp_tosld \
helper_vfp_sqtod \
helper_vfp_tosqd \
helper_vfp_uhtod \
helper_vfp_touhd_round_to_zero \
helper_vfp_touhd \
helper_vfp_ultod \
helper_vfp_tould_round_to_zero \
helper_vfp_tould \
helper_vfp_uqtod \
helper_vfp_touqd \
helper_vfp_shtos \
helper_vfp_toshs_round_to_zero \
helper_vfp_toshs \
helper_vfp_sltos \
helper_vfp_tosls_round_to_zero \
helper_vfp_tosls \
helper_vfp_sqtos \
helper_vfp_tosqs \
helper_vfp_uhtos \
helper_vfp_touhs_round_to_zero \
helper_vfp_touhs \
helper_vfp_ultos \
helper_vfp_touls_round_to_zero \
helper_vfp_touls \
helper_vfp_uqtos \
helper_vfp_touqs \
helper_vfp_sltoh \
helper_vfp_ultoh \
helper_vfp_sqtoh \
helper_vfp_uqtoh \
helper_vfp_toshh \
helper_vfp_touhh \
helper_vfp_toslh \
helper_vfp_toulh \
helper_vfp_tosqh \
helper_vfp_touqh \
helper_set_rmode \
helper_set_neon_rmode \
helper_vfp_fcvt_f16_to_f32 \
helper_vfp_fcvt_f32_to_f16 \
helper_vfp_fcvt_f16_to_f64 \
helper_vfp_fcvt_f64_to_f16 \
helper_recps_f32 \
helper_rsqrts_f32 \
helper_recpe_f16 \
helper_recpe_f32 \
helper_recpe_f64 \
helper_rsqrte_f16 \
helper_rsqrte_f32 \
helper_rsqrte_f64 \
helper_recpe_u32 \
helper_rsqrte_u32 \
helper_vfp_muladds \
helper_vfp_muladdd \
helper_rints_exact \
helper_rintd_exact \
helper_rints \
helper_rintd \
arm_rmode_to_sf \
helper_fjcvtzs \
helper_vjcvt \
helper_frint32_s \
helper_frint64_s \
helper_frint32_d \
helper_frint64_d \
helper_check_hcr_el2_trap \
arm64_reg_reset \
arm64_reg_read \
arm64_reg_write \
mla_op \
mls_op \
sshl_op \
ushl_op \
uqsub_op \
sqsub_op \
uqadd_op \
sqadd_op \
sli_op \
cmtst_op \
sri_op \
usra_op \
ssra_op \
aarch64_translator_ops \
pred_esz_masks \
"

aarch64eb_SYMBOLS=${aarch64_SYMBOLS}


ARCHS="x86_64 arm armeb aarch64 aarch64eb"

for arch in $ARCHS; do

echo "Generating header for $arch"
echo "/* Autogen header for Unicorn Engine - DONOT MODIFY */" > $SOURCE_DIR/qemu/$arch.h
echo "#ifndef UNICORN_AUTOGEN_${arch}_H" >> $SOURCE_DIR/qemu/$arch.h
echo "#define UNICORN_AUTOGEN_${arch}_H" >> $SOURCE_DIR/qemu/$arch.h
echo "#ifndef UNICORN_ARCH_POSTFIX" >> $SOURCE_DIR/qemu/$arch.h
echo "#define UNICORN_ARCH_POSTFIX _$arch" >> $SOURCE_DIR/qemu/$arch.h
echo "#endif" >> $SOURCE_DIR/qemu/$arch.h

for loop in $COMMON_SYMBOLS; do
    echo "#define $loop ${loop}_${arch}" >> $SOURCE_DIR/qemu/$arch.h
done

ARCH_SYMBOLS=$(eval echo '$'"${arch}_SYMBOLS")

#echo ${ARCH_SYMBOLS}

for loop in $ARCH_SYMBOLS; do
    echo "#define $loop ${loop}_${arch}" >> $SOURCE_DIR/qemu/$arch.h
done

echo "#endif" >> $SOURCE_DIR/qemu/$arch.h

done
