name: Crate 📦 Distribution

on:
  push:
    paths-ignore:
      - ".gitignore"
      - "Documentation/**"
      - "README"
      - "CREDITS.TXT"
      - "COPYING_GLIB"
      - "COPYING.LGPL2"
      - "AUTHORS.TXT"
      - "CHANGELOG"
      - "COPYING"
  pull_request:

env:
  UNICORN_VERSION: dev

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.name }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { 
              os: ubuntu-latest,
              arch: x64,
              name: 'Ubuntu x86_64'
            }
    steps:
    - uses: actions/checkout@v2

    - name: '🛠️ Set up Rust'
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        default: true

    - name: '🚧 Cargo test'
      if: "!startsWith(github.ref, 'refs/tags')"
      env:
        UNICORN_LOCAL: uc
      run: |
        cd bindings/rust && cargo test
    
    - name: '📦 Cargo Publish'
      if: startsWith(github.ref, 'refs/tags') && contains(matrix.config.os, 'ubuntu')
      env:
        TOKEN: ${{ secrets.cratesio_token }}
        UNICORN_VERSION: dev
      run: |
        cd bindings/rust && cargo login $TOKEN && cargo test && cargo publish